import OOMP 
import OOMPtags 

######  Auto translated oomp file

newPart = OOMP.oompItem()
newPart.addTag('index','4088')
newPart.addTag('oompID','CAPT-1210-X-UF47-V10')
newPart.addTag('name','SMD (1210) 47 uF Capacitor (Tantalum) 10v')
newPart.addTag('hexID','CTS2U047')
newPart.addTag('oompSort','12100.00004700000000')
newPart.addTag('oompType','CAPT')
newPart.addTag('oompSize','1210')
newPart.addTag('oompColor','X')
newPart.addTag('oompDesc','UF47')
newPart.addTag('oompIndex','V10')
newPart.addTag('oompVersion','99')
newPart.addTag('ooWidth','2.80 mm')
newPart.addTag('ooLength','3.50 mm')
newPart.addTag('ooManufacturer','AVX')
newPart.addTag('ooManufacturerPartNumber','TAJB476K010RNJ')
newPart.addTag('ooMaxVoltage','10 V')
newPart.addTag('ooTolerance','10%')
newPart.addTag('ooSEEEDsku','0130180P1')
newPart.addTag('ooSEEEDdesc','SMD CAP Tantalum 47uF-10V 10%')
newPart.addTag('oompClass','Surface Mount')
newPart.addTag('oompClassCode','SMDS')
newPart.addTag('oompSchem','template;CAPT-XXXX-X-XXXX-XX-schem')
newPart.addTag('ooDesignator','C1')
newPart = OOMPtags.addTags(newPart,"CAPT-1210-X-UF47-V10")
OOMP.parts.append(newPart)
