import OOMP 
import OOMPtags 

######  Auto translated oomp file

newPart = OOMP.oompItem()
pins = 6
newPart.addTag('oompID','ICIC-SP20-X-K1637-01')
newPart.addTag('name','20 Pin SMD (SOP) 7 Segment 8 Digit LED Driver (TM1637)')
newPart.addTag('hexID','ICS1637')
newPart.addTag('oompSort','ICICSP20K1637')
newPart.addTag('oompType','ICIC')
newPart.addTag('oompSize','SP20')
newPart.addTag('oompColor','X')
newPart.addTag('oompDesc','K1637')
newPart.addTag('oompIndex','01')
newPart.addTag('oompVersion','98')
newPart.addTag('ooNumPins','6')
newPart.addTag('ooPin1','GND')
newPart.addTag('ooPin2','SEG1/KS1')
newPart.addTag('ooPin3','SEG2/KS2')
newPart.addTag('ooPin4','SEG3/KS3')
newPart.addTag('ooPin5','SEG4/KS4')
newPart.addTag('ooPin6','SEG5/KS5')
newPart.addTag('ooPin7','SEG6/KS6')
newPart.addTag('ooPin8','SEG7/KS7')
newPart.addTag('ooPin9','SEG8/KS8')
newPart.addTag('ooPin10','GRID6')
newPart.addTag('ooPin11','GRID5')
newPart.addTag('ooPin12','GRID4')
newPart.addTag('ooPin13','GRID3')
newPart.addTag('ooPin14','GRID2')
newPart.addTag('ooPin15','GRID1')
newPart.addTag('ooPin16','VDD')
newPart.addTag('ooPin17','DIO')
newPart.addTag('ooPin18','CLK')
newPart.addTag('ooPin19','K1')
newPart.addTag('ooPin20','K2')
newPart.addTag('oompBbls','template;ICIC-SP20-X-XXXX-01-bbls')
newPart.addTag('oompDiag','template;ICIC-SP20-X-XXXX-01-diag')
newPart.addTag('oompIden','template;ICIC-SP20-X-XXXX-01-iden')
newPart.addTag('oompSimp','template;ICIC-SP20-X-XXXX-01-simp')
newPart.addTag('ooPackageMarking','TM1637')
newPart.addTag('ooDesignator','U1')
newPart = OOMPtags.addTags(newPart,"ICIC-SP20-X-K1637-01",pins = 6)
OOMP.parts.append(newPart)
