import OOMP 
import OOMPtags 

######  Auto translated oomp file

newPart = OOMP.oompItem()
pitch = 2.54 
pins = 28
newPart.addTag('index','4321')
newPart.addTag('oompID','ICIC-DI28-X-K328-01')
newPart.addTag('name','28 Pin DIP AtMega328P')
newPart.addTag('hexID','IC328')
newPart.addTag('oompSort','ATMega 328')
newPart.addTag('oompType','ICIC')
newPart.addTag('oompSize','DI28')
newPart.addTag('oompColor','X')
newPart.addTag('oompDesc','K328')
newPart.addTag('oompIndex','01')
newPart.addTag('oompVersion','99')
newPart.addTag('ooPitch','2.54 mm')
newPart.addTag('ooWidth','34.7 mm')
newPart.addTag('ooHeight','4.5 mm')
newPart.addTag('ooLength','7.25 mm')
newPart.addTag('ooManufacturer','C-ATME')
newPart.addTag('ooManufacturerPartNumber','ATMEGA328P-PU')
newPart.addTag('ooNumPins','28')
newPart.addTag('ooNumPins','28')
newPart.addTag('ooFootprint','OOMP-ICIC-DI28-X-XXXX-01')
newPart.addTag('useID','1')
newPart.addTag('importance','1')
newPart.addTag('useTitle','Arduino')
newPart.addTag('useDescription','Used as the Microcontroller in the Arduino UNO')
newPart.addTag('ooSEEEDsku','1030050P1')
newPart.addTag('ooSEEEDdesc','IC MCU 8BIT 32KB FLASH')
newPart.addTag('ooSEEED3dModel','http://www.seeedstudio.com/wiki/File:DIP28.zip')
newPart.addTag('oompClass','Through Hole Component')
newPart.addTag('oompClassCode','THTH')
newPart.addTag('ooPin1','PC6')
newPart.addTag('ooPin2','PD0')
newPart.addTag('ooPin3','PD1')
newPart.addTag('ooPin4','PD2')
newPart.addTag('ooPin5','PD3')
newPart.addTag('ooPin6','PD4')
newPart.addTag('ooPin7','VCC')
newPart.addTag('ooPin8','GND')
newPart.addTag('ooPin9','PB6')
newPart.addTag('ooPin10','PB7')
newPart.addTag('ooPin11','PD5')
newPart.addTag('ooPin12','PD6')
newPart.addTag('ooPin13','PD7')
newPart.addTag('ooPin14','PB0')
newPart.addTag('ooPin15','PB1')
newPart.addTag('ooPin16','PB2')
newPart.addTag('ooPin17','PB3')
newPart.addTag('ooPin18','PB4')
newPart.addTag('ooPin19','PB5')
newPart.addTag('ooPin20','AVCC')
newPart.addTag('ooPin21','AREF')
newPart.addTag('ooPin22','GND')
newPart.addTag('ooPin23','PC0')
newPart.addTag('ooPin24','PC1')
newPart.addTag('ooPin25','PC2')
newPart.addTag('ooPin26','PC3')
newPart.addTag('ooPin27','PC4')
newPart.addTag('ooPin28','PC5')
newPart.addTag('oompDiag','template;ICIC-DI28-X-XXXX-01-diag')
newPart.addTag('ooPackageMarking','ATMEGA328')
newPart.addTag('ooDesignator','U1')
newPart = OOMPtags.addTags(newPart,"ICIC-DI28-X-K328-01",pitch = 2.54 ,pins = 28)
OOMP.parts.append(newPart)
