import OOMP 
import OOMPtags 

######  Auto translated oomp file

newPart = OOMP.oompItem()
pitch = 2.54
pins = 5
newPart.addTag('index','9876')
newPart.addTag('oompID','HEAD-I01-X-PI05-01')
newPart.addTag('name','2.54 mm 5 Pin Header')
newPart.addTag('hexID','H05')
newPart.addTag('oompSort','010105')
newPart.addTag('oompType','HEAD')
newPart.addTag('oompSize','I01')
newPart.addTag('oompColor','X')
newPart.addTag('oompDesc','PI05')
newPart.addTag('oompIndex','01')
newPart.addTag('oompVersion','99')
newPart.addTag('ooPitch','2.54')
newPart.addTag('ooPinHeight','11.60')
newPart.addTag('ooPinWidth','0.64')
newPart.addTag('ooPinOffset','1.53')
newPart.addTag('ooNumPins','5')
newPart.addTag('ooFootprint','OOMP-HEAD-I01-X-PI05-01')
newPart.addTag('oompClass','Through Hole Component')
newPart.addTag('oompClassCode','THTH')
newPart.addTag('oompBbls','variable;clear')
newPart.addTag('oompBbls','variable;pins;5')
newPart.addTag('oompBbls','template;XXXX-I01-X-XX-01-bbls')
newPart.addTag('oompDiag','variable;clear')
newPart.addTag('oompDiag','variable;pins;5')
newPart.addTag('oompDiag','template;HEAD-I01-X-XX-01-diag')
newPart.addTag('oompIden','variable;clear')
newPart.addTag('oompIden','variable;pins;5')
newPart.addTag('oompIden','template;XXXX-I01-X-XX-01-iden')
newPart.addTag('oompSchem','variable;clear')
newPart.addTag('oompSchem','variable;pins;5')
newPart.addTag('oompSchem','template;XXXX-XX-X-XX-01-PINS-ODD-schem')
newPart.addTag('oompSimp','variable;clear')
newPart.addTag('oompSimp','variable;pins;5')
newPart.addTag('oompSimp','template;XXXX-I01-X-XX-01-simp')
newPart.addTag('ooDesignator','J1')
newPart.addTag('schematicSymbol','HEAD-XX-X-PI05-XX')
newPart.addTag('pcbFootprint','HEAD-I01-X-PI05-01')
newPart = OOMPtags.addTags(newPart,"HEAD-I01-X-PI05-01",pitch = 2.54,pins = 5)
OOMP.parts.append(newPart)
