import OOMP 
import OOMPtags 

######  Auto translated oomp file

newPart = OOMP.oompItem()
newPart.addTag('index','4089')
newPart.addTag('oompID','CAPT-2312-X-UF100-V10')
newPart.addTag('name','SMD (2312) 100 uF Capacitor (Tantalum) 10v')
newPart.addTag('hexID','CTS3U100')
newPart.addTag('oompSort','23120.00010000000000')
newPart.addTag('oompType','CAPT')
newPart.addTag('oompSize','2312')
newPart.addTag('oompColor','X')
newPart.addTag('oompDesc','UF100')
newPart.addTag('oompIndex','V10')
newPart.addTag('oompVersion','99')
newPart.addTag('ooWidth','3.20 mm')
newPart.addTag('ooLength','6.00 mm')
newPart.addTag('ooManufacturer','AVX')
newPart.addTag('ooManufacturerPartNumber','TAJC107K010RNJ')
newPart.addTag('ooMaxVoltage','10 V')
newPart.addTag('ooTolerance','10%')
newPart.addTag('ooSEEEDsku','0130170P1')
newPart.addTag('ooSEEEDdesc','SMD CAP Tantalum 100uF-10V 10%')
newPart.addTag('oompClass','Surface Mount')
newPart.addTag('oompClassCode','SMDS')
newPart.addTag('oompSchem','template;CAPT-XXXX-X-XXXX-XX-schem')
newPart.addTag('ooDesignator','C1')
newPart = OOMPtags.addTags(newPart,"CAPT-2312-X-UF100-V10")
OOMP.parts.append(newPart)
