import OOMP 
import OOMPtags 

######  Auto translated oomp file

newPart = OOMP.oompItem()
newPart.addTag('index','4114')
newPart.addTag('oompID','RESE-0603-X-O330-67')
newPart.addTag('name','SMD (0603) 33 Ohm Resistor 1%')
newPart.addTag('hexID','R6330A')
newPart.addTag('oompSort','ZZZ06030000033')
newPart.addTag('oompType','RESE')
newPart.addTag('oompSize','0603')
newPart.addTag('oompColor','X')
newPart.addTag('oompDesc','O330')
newPart.addTag('oompIndex','67')
newPart.addTag('oompVersion','99')
newPart.addTag('ooWidth','0.8 mm')
newPart.addTag('ooLength','1.6 mm')
newPart.addTag('ooManufacturer','YageoYageo')
newPart.addTag('ooManufacturerPartNumber','RC0603FR-07330RL')
newPart.addTag('ooMaterial','Thick Film')
newPart.addTag('ooPowerRating','1/10 W')
newPart.addTag('ooTolerance','5%')
newPart.addTag('ooSEEEDsku','0011330P1')
newPart.addTag('ooSEEEDdesc','SMD RES 330R-1%-1/10W')
newPart.addTag('ooSEEED3dModel','http://www.seeedstudio.com/wiki/File:Resistor0603.zip')
newPart.addTag('oompClass','Surface Mount')
newPart.addTag('oompClassCode','SMDS')
newPart.addTag('oompBbls','template;XXXX-0603-X-XXXX-XX-bbls')
newPart.addTag('oompDiag','template;XXXX-0603-X-XXXX-XX-diag')
newPart.addTag('oompIden','template;XXXX-0603-X-XXXX-XX-iden')
newPart.addTag('oompSchem','template;RESE-XXXX-X-XXXX-XX-schem')
newPart.addTag('oompSimp','template;XXXX-0603-X-XXXX-XX-simp')
newPart.addTag('ooDesignator','R1')
newPart = OOMPtags.addTags(newPart,"RESE-0603-X-O330-67")
OOMP.parts.append(newPart)
