import OOMP
newPart = OOMP.getPartByID("LEDS-0805-Y-STAN-01")

newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-1272-STAN-01', 'ID': 'LED4'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2078-STAN-01', 'ID': 'LED1'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2267-STAN-01', 'ID': 'LED1'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2466-STAN-01', 'ID': 'RXLED'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2466-STAN-01', 'ID': 'TXLED'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2999-STAN-01', 'ID': 'D2'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-3382-STAN-01', 'ID': 'RXLED'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-3382-STAN-01', 'ID': 'TXLED'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-3458-STAN-01', 'ID': 'D1'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-3458-STAN-01', 'ID': 'D5'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-3505-STAN-01', 'ID': 'RXLED'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-3505-STAN-01', 'ID': 'TXLED'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-4000-STAN-01', 'ID': 'RXLED'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-4000-STAN-01', 'ID': 'TXLED'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-4064-STAN-01', 'ID': 'RXLED'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-4064-STAN-01', 'ID': 'TXLED'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-659-STAN-01', 'ID': 'RXLED'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-659-STAN-01', 'ID': 'TXLED'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ARDU-LEO-STAN-01', 'ID': 'L'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ARDU-LEO-STAN-01', 'ID': 'RX'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ARDU-LEO-STAN-01', 'ID': 'TX'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ARDU-MICRO-STAN-01', 'ID': 'RX'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ARDU-MICRO-STAN-01', 'ID': 'TX'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ARDU-UNO-REV3-01', 'ID': 'L'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ARDU-UNO-REV3-01', 'ID': 'RX'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ARDU-UNO-REV3-01', 'ID': 'TX'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ARDU-UNO-REV3-SM', 'ID': 'L'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ARDU-UNO-REV3-SM', 'ID': 'RX'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ARDU-UNO-REV3-SM', 'ID': 'TX'})