import OOMP 
import OOMPtags 

######  Auto translated oomp file

newPart = OOMP.oompItem()
pins = 2
newPart.addTag('index','9876')
newPart.addTag('oompID','LEDS-0805-Y-STAN-01')
newPart.addTag('name','SMD (0805) Yellow LED')
newPart.addTag('hexID','L85Y')
newPart.addTag('oompSort','0805Y')
newPart.addTag('oompType','LEDS')
newPart.addTag('oompSize','0805')
newPart.addTag('oompColor','Y')
newPart.addTag('oompDesc','STAN')
newPart.addTag('oompIndex','01')
newPart.addTag('oompVersion','99')
newPart.addTag('oompSkip','true')
newPart.addTag('ooWidth','2 mm')
newPart.addTag('ooHeight','0.8 mm')
newPart.addTag('ooLength','1.25 mm')
newPart.addTag('ooNumPins','2')
newPart.addTag('ooLensColor','')
newPart.addTag('ooForwardVoltage','2.4')
newPart.addTag('ooForwardCurrent','25 mA')
newPart.addTag('ooIntensity','')
newPart.addTag('ooPowerAngle','')
newPart.addTag('ooWavelength','')
newPart.addTag('oompClass','Surface Mount')
newPart.addTag('oompClassCode','SMDS')
newPart.addTag('oompBbls','template;XXXX-0805-X-XXXX-XX-bbls')
newPart.addTag('oompDiag','template;XXXX-0805-X-XXXX-XX-diag')
newPart.addTag('oompIden','template;XXXX-0805-X-XXXX-XX-iden')
newPart.addTag('oompSchem','template;LEDS-XXXX-X-XXXX-XX-schem')
newPart.addTag('oompSimp','template;XXXX-0805-X-XXXX-XX-simp')
newPart.addTag('ooDesignator','D1')
newPart = OOMPtags.addTags(newPart,"LEDS-0805-Y-STAN-01",pins = 2)
OOMP.parts.append(newPart)
