import OOMP 
import OOMPtags 

######  Auto translated oomp file

newPart = OOMP.oompItem()
pitch = 2.54 
newPart.addTag('index','3952')
newPart.addTag('oompID','CRHO-I01-B-PI10-01')
newPart.addTag('name','2.54 mm 10 Pin Black Crimp Housing')
newPart.addTag('hexID','CH10')
newPart.addTag('oompSort','010110')
newPart.addTag('oompType','CRHO')
newPart.addTag('oompSize','I01')
newPart.addTag('oompColor','B')
newPart.addTag('oompDesc','PI10')
newPart.addTag('oompIndex','01')
newPart.addTag('oompVersion','10')
newPart.addTag('ooPitch','2.54 mm')
newPart.addTag('ooWidth','25.6 mm')
newPart.addTag('ooHeight','14 mm')
newPart.addTag('ooDepth','2.5 mm')
newPart.addTag('ooMaterial','Plastic')
newPart.addTag('ooTerminalStyle','DuPont')
newPart.addTag('ooMaxCurrent','3 A')
newPart.addTag('ooMaxVoltage','250 V')
newPart.addTag('oompAbout','These ten pin connectors are often used simply when you find you have ten wires that need connecting. They are occasionally useful when paired with a six pin header, to connect a parallel LCD to a project.')
newPart.addTag('oompClass','Through Hole Component')
newPart.addTag('oompClassCode','THTH')
newPart.addTag('oompBbls','variable;clear')
newPart.addTag('oompBbls','variable;pins;10')
newPart.addTag('oompBbls','template;XXXX-I01-X-XX-01-bbls')
newPart.addTag('oompDiag','variable;clear')
newPart.addTag('oompDiag','variable;pins;10')
newPart.addTag('oompDiag','template;CRHO-I01-X-XX-01-diag')
newPart.addTag('drawItem','variable;clear')
newPart.addTag('drawItem','variable;pins;10')
newPart.addTag('drawItem','template;XXXX-I01-X-XX-01-iden')
newPart.addTag('oompSchem','variable;clear')
newPart.addTag('oompSchem','variable;pins;10')
newPart.addTag('oompSchem','template;XXXX-XX-X-XX-01-PINS-EVEN-schem')
newPart.addTag('oompSimp','variable;clear')
newPart.addTag('oompSimp','variable;pins;10')
newPart.addTag('oompSimp','template;XXXX-I01-X-XX-01-simp')
newPart.addTag('ooDesignator','J1')
newPart = OOMPtags.addTags(newPart,"CRHO-I01-B-PI10-01",pitch = 2.54 )
OOMP.parts.append(newPart)
