import OOMP 
import OOMPtags 

######  Auto translated oomp file

newPart = OOMP.oompItem()
newPart.addTag('index','4325')
newPart.addTag('oompID','VREG-SO23-X-V33D-A5D')
newPart.addTag('name','SMD (SOT-23) 3.3v Voltage Regulator 500 mA')
newPart.addTag('hexID','VS235')
newPart.addTag('oompSort','SO233.300.500')
newPart.addTag('oompType','VREG')
newPart.addTag('oompSize','SO23')
newPart.addTag('oompColor','X')
newPart.addTag('oompDesc','V33D')
newPart.addTag('oompIndex','A5D')
newPart.addTag('oompVersion','99')
newPart.addTag('ooManufacturer','C-TORE')
newPart.addTag('ooManufacturerPartNumber','XC6206P332MR-G')
newPart.addTag('ooSEEEDsku','1300260P1')
newPart.addTag('ooSEEEDdesc','')
newPart.addTag('ooSEEED3dModel','http://www.seeedstudio.com/wiki/File:SOT23.zip')
newPart.addTag('oompClass','Surface Mount')
newPart.addTag('oompClassCode','SMDS')
newPart.addTag('ooPin1','VSS')
newPart.addTag('ooPin2','VOUT')
newPart.addTag('ooPin3','VIN')
newPart.addTag('oompBbls','template;XXXX-SO23-X-XXXX-01-bbls')
newPart.addTag('oompDiag','template;XXXX-SO23-X-XXXX-01-diag')
newPart.addTag('oompIden','template;XXXX-SO23-X-XXXX-01-iden')
newPart.addTag('oompSimp','template;XXXX-SO23-X-XXXX-01-simp')
newPart.addTag('ooPackageMarking','662K')
newPart.addTag('ooDesignator','D1')
newPart = OOMPtags.addTags(newPart,"VREG-SO23-X-V33D-A5D")
OOMP.parts.append(newPart)
