import OOMP 
import OOMPtags 

######  Auto translated oomp file

newPart = OOMP.oompItem()
newPart.addTag('oompID','DIOD-SO23-X-ESDP-01')
newPart.addTag('name','SMD (SOT-23) ESD Protection Diode')
newPart.addTag('hexID','DS2EP')
newPart.addTag('oompSort','')
newPart.addTag('oompClass','Surface Mount')
newPart.addTag('oompClassCode','SMDS')
newPart.addTag('oompType','DIOD')
newPart.addTag('oompSize','SO23')
newPart.addTag('oompColor','X')
newPart.addTag('oompDesc','ESDP')
newPart.addTag('oompIndex','01')
newPart.addTag('oompVersion','40')
newPart.addTag('ooPin1','C')
newPart.addTag('ooPin2','C')
newPart.addTag('ooPin3','A')
newPart.addTag('oompBbls','template;XXXX-SO23-X-XXXX-01-bbls')
newPart.addTag('oompDiag','template;XXXX-SO23-X-XXXX-01-diag')
newPart.addTag('oompIden','template;XXXX-SO23-X-XXXX-01-iden')
newPart.addTag('oompSchem','template;DIOS-XXXX-X-ESDP-XX-schem')
newPart.addTag('oompSimp','template;XXXX-SO23-X-XXXX-01-simp')
newPart.addTag('ooPackageMarking','5M')
newPart.addTag('ooDesignator','D1')
newPart = OOMPtags.addTags(newPart,"DIOD-SO23-X-ESDP-01")
OOMP.parts.append(newPart)
