import OOMP 
import OOMPtags 

######  Auto translated oomp file

newPart = OOMP.oompItem()
newPart.addTag('index','4296')
newPart.addTag('oompID','BUTA-07-X-SMDS-01')
newPart.addTag('name','7 mm SMD Pushbutton (Tactile)')
newPart.addTag('hexID','B7S')
newPart.addTag('oompSort','0707')
newPart.addTag('oompType','BUTA')
newPart.addTag('oompSize','07')
newPart.addTag('oompColor','X')
newPart.addTag('oompDesc','SMDS')
newPart.addTag('oompIndex','01')
newPart.addTag('oompVersion','99')
newPart.addTag('ooWidth','3.5 mm')
newPart.addTag('ooHeight','3.55 mm')
newPart.addTag('ooLength','7 mm')
newPart.addTag('ooManufacturer','C-BEST')
newPart.addTag('ooManufacturerPartNumber','Shenzhen Best Electronics')
newPart.addTag('useID','1')
newPart.addTag('importance','1')
newPart.addTag('useTitle','Reset Button')
newPart.addTag('useDescription','a reset button for a microcontroller.')
newPart.addTag('ooSEEEDsku','3100060P1')
newPart.addTag('ooSEEEDdesc','SMD Button	')
newPart.addTag('oompAbout','A commonly used surface mount pushbutton. With the button on the side rather than the top.')
newPart.addTag('ooSEEED3dModel','http://www.seeedstudio.com/wiki/File:4P-SMD-7.0X3.5X3.5H-90D.zip')
newPart.addTag('oompClass','Surface Mount')
newPart.addTag('oompClassCode','SMDS')
newPart.addTag('oompSchem','template;BUTA-XXXX-X-02PI-XX-schem')
newPart.addTag('ooDesignator','S')
newPart.addTag('oompSymbol','twoSidedPackage;##ooNumPins@@/2')
newPart.addTag('ooPin1','.')
newPart.addTag('ooPin2','.')
newPart = OOMPtags.addTags(newPart,"BUTA-07-X-SMDS-01")
OOMP.parts.append(newPart)
