import OOMP
newPart = OOMP.getPartByID("RESE-0805-X-O101-01")

newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-1381-STAN-01', 'ID': 'R6'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-1381-STAN-01', 'ID': 'R7'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-1601-STAN-01', 'ID': 'R1'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-1601-STAN-01', 'ID': 'R2'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-1601-STAN-01', 'ID': 'R3'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-1601-STAN-01', 'ID': 'R4'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-1778-STAN-01', 'ID': 'R1'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-1778-STAN-01', 'ID': 'R2'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-1788-STAN-01', 'ID': 'R6'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-1788-STAN-01', 'ID': 'R7'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2130-STAN-01', 'ID': 'R1'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2130-STAN-01', 'ID': 'R2'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2298-STAN-01', 'ID': 'R1'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2298-STAN-01', 'ID': 'R2'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2298-STAN-01', 'ID': 'R3'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2298-STAN-01', 'ID': 'R4'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2315-STAN-01', 'ID': 'R4'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2315-STAN-01', 'ID': 'R5'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2315-STAN-01', 'ID': 'R7'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2315-STAN-01', 'ID': 'R8'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2455-STAN-01', 'ID': 'R1'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2455-STAN-01', 'ID': 'R2'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2455-STAN-01', 'ID': 'R3'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2455-STAN-01', 'ID': 'R4'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2616-STAN-01', 'ID': 'R1'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2616-STAN-01', 'ID': 'R2'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2616-STAN-01', 'ID': 'R15'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2616-STAN-01', 'ID': 'R16'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2616-STAN-01', 'ID': 'R17'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2616-STAN-01', 'ID': 'R18'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-3263-STAN-01', 'ID': 'R1'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-3263-STAN-01', 'ID': 'R2'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-3678-STAN-01', 'ID': 'R4'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-3678-STAN-01', 'ID': 'R6'})