import OOMP 
import OOMPtags 

######  Auto translated oomp file

newPart = OOMP.oompItem()
pitch = 2.54 
newPart.addTag('index','3947')
newPart.addTag('oompID','CRHO-I01-B-PI03-01')
newPart.addTag('name','2.54 mm 3 Pin Black Crimp Housing')
newPart.addTag('hexID','CH03')
newPart.addTag('oompSort','010103')
newPart.addTag('oompType','CRHO')
newPart.addTag('oompSize','I01')
newPart.addTag('oompColor','B')
newPart.addTag('oompDesc','PI03')
newPart.addTag('oompIndex','01')
newPart.addTag('oompVersion','10')
newPart.addTag('ooPitch','2.54 mm')
newPart.addTag('ooWidth','7.82 mm')
newPart.addTag('ooHeight','14 mm')
newPart.addTag('ooDepth','2.5 mm')
newPart.addTag('ooMaterial','Plastic')
newPart.addTag('ooTerminalStyle','DuPont')
newPart.addTag('ooMaxCurrent','3 A')
newPart.addTag('ooMaxVoltage','250 V')
newPart.addTag('oompAbout','This three pin housing is great for connecting externally mounted potentiometers. Also commonly found on hobby servos or any item requiring power (+,gnd) and a signal line. (WS2812 LED strings, analog temperature sensors etc.)')
newPart.addTag('oompClass','Through Hole Component')
newPart.addTag('oompClassCode','THTH')
newPart.addTag('oompBbls','variable;clear')
newPart.addTag('oompBbls','variable;pins;3')
newPart.addTag('oompBbls','template;XXXX-I01-X-XX-01-bbls')
newPart.addTag('oompDiag','variable;clear')
newPart.addTag('oompDiag','variable;pins;3')
newPart.addTag('oompDiag','template;CRHO-I01-X-XX-01-diag')
newPart.addTag('drawItem','variable;clear')
newPart.addTag('drawItem','variable;pins;3')
newPart.addTag('drawItem','template;XXXX-I01-X-XX-01-iden')
newPart.addTag('oompSchem','variable;clear')
newPart.addTag('oompSchem','variable;pins;3')
newPart.addTag('oompSchem','template;XXXX-XX-X-XX-01-PINS-ODD-schem')
newPart.addTag('oompSimp','variable;clear')
newPart.addTag('oompSimp','variable;pins;3')
newPart.addTag('oompSimp','template;XXXX-I01-X-XX-01-simp')
newPart.addTag('ooDesignator','J1')
newPart = OOMPtags.addTags(newPart,"CRHO-I01-B-PI03-01",pitch = 2.54 )
OOMP.parts.append(newPart)
