import OOMP
newPart = OOMP.getPartByID("HEAD-I01-X-PI20-01")

newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-1325-STAN-01', 'ID': 'JP2'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-1325-STAN-01', 'ID': 'JP3'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-1743-STAN-01', 'ID': 'JP1'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-1743-STAN-01', 'ID': 'JP2'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-1770-STAN-01', 'ID': '1X20BREAKOUT'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2050-STAN-01', 'ID': 'JP1'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2050-STAN-01', 'ID': 'JP2'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2090-STAN-01', 'ID': 'JP1'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2090-STAN-01', 'ID': 'JP2'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2478-STAN-01', 'ID': 'JP1'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2478-STAN-01', 'ID': 'JP2'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-10705-STAN-01', 'ID': 'JP3'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-10705-STAN-01', 'ID': 'JP4'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-11525-STAN-01', 'ID': 'JP2'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-11525-STAN-01', 'ID': 'JP3'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-12849-STAN-01', 'ID': 'JP1'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-12849-STAN-01', 'ID': 'JP2'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-14153-STAN-01', 'ID': 'J4'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-14153-STAN-01', 'ID': 'J9'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-14153-STAN-01', 'ID': 'J10'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-14153-STAN-01', 'ID': 'J11'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-14153-STAN-01', 'ID': 'J12'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-14153-STAN-01', 'ID': 'J13'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-14430-STAN-01', 'ID': 'J1'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-14430-STAN-01', 'ID': 'J3'})