import OOMP 
import OOMPtags 

######  Auto translated oomp file

newPart = OOMP.oompItem()
pitch = 0.65 
pins = 32
newPart.addTag('index','4326')
newPart.addTag('oompID','ICIC-TQ32-X-K328-01')
newPart.addTag('name','32 Pin SMD (TQFP) AtMega328P')
newPart.addTag('hexID','ICS328')
newPart.addTag('oompSort','AtMega 328 SMD')
newPart.addTag('oompType','ICIC')
newPart.addTag('oompSize','TQ32')
newPart.addTag('oompColor','X')
newPart.addTag('oompDesc','K328')
newPart.addTag('oompIndex','01')
newPart.addTag('oompVersion','99')
newPart.addTag('ooManufacturer','C-ATME')
newPart.addTag('ooManufacturerPartNumber','ATMEGA328P-AU')
newPart.addTag('ooSEEEDsku','1030060P1')
newPart.addTag('ooSEEEDdesc','IC MCU 8BIT 32KB FLASH 32TQFP')
newPart.addTag('ooSEEED3dModel','http://www.seeedstudio.com/wiki/File:TQFP32.zip')
newPart.addTag('oompClass','Surface Mount')
newPart.addTag('oompClassCode','SMDS')
newPart.addTag('ooPitch','0.65 mm')
newPart.addTag('ooPadWidth','1 mm')
newPart.addTag('ooPadHeight','0.32 mm')
newPart.addTag('ooPin1','PD3')
newPart.addTag('ooPin2','PD4')
newPart.addTag('ooPin3','GND')
newPart.addTag('ooPin4','VCC')
newPart.addTag('ooPin5','GND')
newPart.addTag('ooPin6','VCC')
newPart.addTag('ooPin7','PB6')
newPart.addTag('ooPin8','PB7')
newPart.addTag('ooPin9','PD5')
newPart.addTag('ooPin10','PD6')
newPart.addTag('ooPin11','PD7')
newPart.addTag('ooPin12','PB0')
newPart.addTag('ooPin13','PB1')
newPart.addTag('ooPin14','PB2')
newPart.addTag('ooPin15','PB3')
newPart.addTag('ooPin16','PB4')
newPart.addTag('ooPin17','PB5')
newPart.addTag('ooPin18','AVCC')
newPart.addTag('ooPin19','ADC6')
newPart.addTag('ooPin20','AREF')
newPart.addTag('ooPin21','GND')
newPart.addTag('ooPin22','ADC7')
newPart.addTag('ooPin23','PC0')
newPart.addTag('ooPin24','PC1')
newPart.addTag('ooPin25','PC2')
newPart.addTag('ooPin26','PC3')
newPart.addTag('ooPin27','PC4')
newPart.addTag('ooPin28','PC5')
newPart.addTag('ooPin29','PC5')
newPart.addTag('ooPin30','PD0')
newPart.addTag('ooPin31','PD1')
newPart.addTag('ooPin32','PD2')
newPart.addTag('ooNumPins','32')
newPart.addTag('oompDiag','template;ICIC-TQ32-X-XXXX-01-diag')
newPart.addTag('oompSymbol','twoSidedPackage;##ooNumPins@@')
newPart.addTag('oompFootprint','TQSMDPackage;##ooNumPins@@;##ooPitch@@;##ooPadWidth@@;##ooPadHeight@@')
newPart.addTag('ooPackageMarking','ATMEGA328')
newPart.addTag('ooDesignator','U1')
newPart = OOMPtags.addTags(newPart,"ICIC-TQ32-X-K328-01",pitch = 0.65 ,pins = 32)
OOMP.parts.append(newPart)
