import OOMP
newPart = OOMP.getPartByID("RESE-0805-X-O221-01")

newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-1588-STAN-01', 'ID': 'R8'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-1588-STAN-01', 'ID': 'R10'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-1628-STAN-01', 'ID': 'R8'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-1628-STAN-01', 'ID': 'R10'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-815-STAN-01', 'ID': 'R10'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-815-STAN-01', 'ID': 'R11'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-815-STAN-01', 'ID': 'R12'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-815-STAN-01', 'ID': 'R13'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-815-STAN-01', 'ID': 'R14'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-815-STAN-01', 'ID': 'R15'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-815-STAN-01', 'ID': 'R16'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-815-STAN-01', 'ID': 'R17'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-815-STAN-01', 'ID': 'R18'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-815-STAN-01', 'ID': 'R19'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-815-STAN-01', 'ID': 'R20'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-815-STAN-01', 'ID': 'R21'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-815-STAN-01', 'ID': 'R22'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-815-STAN-01', 'ID': 'R23'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-815-STAN-01', 'ID': 'R24'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-815-STAN-01', 'ID': 'R25'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-815-STAN-01', 'ID': 'R26'})