import OOMP
newPart = OOMP.getPartByID("LEDS-0805-L-STAN-01")

newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-1588-STAN-01', 'ID': 'LED3'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-1588-STAN-01', 'ID': 'LED4'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-1628-STAN-01', 'ID': 'LED3'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-1628-STAN-01', 'ID': 'LED4'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-1944-STAN-01', 'ID': 'PWR'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-1963-STAN-01', 'ID': 'NETSTAT'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2078-STAN-01', 'ID': 'LED3'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2218-STAN-01', 'ID': 'LED3'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2260-STAN-01', 'ID': 'LED3'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2267-STAN-01', 'ID': 'LED4'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2406-STAN-01', 'ID': 'LED3'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2465-STAN-01', 'ID': 'LED2'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2468-STAN-01', 'ID': 'NETSTAT'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2487-STAN-01', 'ID': 'D2'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2542-STAN-01', 'ID': 'PWRSTAT'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2633-STAN-01', 'ID': 'D2'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2636-STAN-01', 'ID': 'NETSTAT'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2661-STAN-01', 'ID': 'D2'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2746-STAN-01', 'ID': 'D2'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2829-STAN-01', 'ID': 'D2'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2995-STAN-01', 'ID': 'D3'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-3027-STAN-01', 'ID': 'NETSTAT'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ARDU-MICRO-STAN-01', 'ID': 'ON'})