import OOMP
newPart = OOMP.getPartByID("HEAD-I01-X-PI2X03-01")

newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-1429-STAN-01', 'ID': 'JP2'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-1429-STAN-01', 'ID': 'JP3'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-1429-STAN-01', 'ID': 'JP4'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-1429-STAN-01', 'ID': 'JP5'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-1429-STAN-01', 'ID': 'JP6'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-1429-STAN-01', 'ID': 'JP7'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-1429-STAN-01', 'ID': 'JP8'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-1429-STAN-01', 'ID': 'JP9'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-1455-STAN-01', 'ID': 'JP2'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-1455-STAN-01', 'ID': 'JP3'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-1455-STAN-01', 'ID': 'JP5'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-1455-STAN-01', 'ID': 'JP8'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-1588-STAN-01', 'ID': 'JP5'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-1628-STAN-01', 'ID': 'JP5'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2466-STAN-01', 'ID': 'ICSP'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-3382-STAN-01', 'ID': 'ICSP'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-3505-STAN-01', 'ID': 'ICSP'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-4000-STAN-01', 'ID': 'ICSP'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-4064-STAN-01', 'ID': 'ICSP'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-4775-STAN-01', 'ID': 'ICSP'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-4985-STAN-01', 'ID': 'JP1'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-4985-STAN-01', 'ID': 'JP2'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-659-STAN-01', 'ID': 'JP1'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-795-STAN-01', 'ID': 'JP3'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-91-STAN-01', 'ID': 'JP3'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ARDU-LEO-STAN-01', 'ID': 'ICSP'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ARDU-MICRO-STAN-01', 'ID': 'J4'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ARDU-UNO-REV3-01', 'ID': 'ICSP'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ARDU-UNO-REV3-01', 'ID': 'ICSP1'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ARDU-UNO-REV3-SM', 'ID': 'ICSP'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ARDU-UNO-REV3-SM', 'ID': 'ICSP1'})