import OOMP
newPart = OOMP.getPartByID("RESE-0603-X-O221-01")

newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-4566-STAN-01', 'ID': 'R1'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-4740-STAN-01', 'ID': 'R2'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-4832-STAN-01', 'ID': 'R1'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-10124-STAN-01', 'ID': 'R4'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-12898-STAN-01', 'ID': 'R1'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-12898-STAN-01', 'ID': 'R2'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-12898-STAN-01', 'ID': 'R3'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-12898-STAN-01', 'ID': 'R4'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-13044-STAN-01', 'ID': 'R10'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-13810-STAN-01', 'ID': 'R45'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-13810-STAN-01', 'ID': 'R46'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-13810-STAN-01', 'ID': 'R47'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-13810-STAN-01', 'ID': 'R48'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-14155-STAN-01', 'ID': 'R7'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-14155-STAN-01', 'ID': 'R8'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-14155-STAN-01', 'ID': 'R9'})