import OOMP 
import OOMPtags 

######  Auto translated oomp file

newPart = OOMP.oompItem()
pins = 4
newPart.addTag('index','4315')
newPart.addTag('oompID','BUTA-06-X-SMDS-01')
newPart.addTag('name','6 mm SMD Pushbutton (Tactile)')
newPart.addTag('hexID','B06')
newPart.addTag('oompSort','0606')
newPart.addTag('oompType','BUTA')
newPart.addTag('oompSize','06')
newPart.addTag('oompColor','X')
newPart.addTag('oompDesc','SMDS')
newPart.addTag('oompIndex','01')
newPart.addTag('oompVersion','99')
newPart.addTag('ooWidth','6.2 mm')
newPart.addTag('ooHeight','3.5 mm')
newPart.addTag('ooLength','6.2 mm')
newPart.addTag('ooNumPins','4')
newPart.addTag('useID','1')
newPart.addTag('useID','2')
newPart.addTag('importance','1')
newPart.addTag('importance','2')
newPart.addTag('useTitle','Reset Button')
newPart.addTag('useTitle','Keypad Button')
newPart.addTag('useDescription','a reset button for a microcontroller.')
newPart.addTag('useDescription','a button on a keypad.')
newPart.addTag('oompAbout','<![CDATA[A commonly used through surface mount tactile pushbutton. For a through hole version of this part see <a href="http://learn.oomlout.co.uk/OO/Projects/oomp/part/BUTA-06-X-STAN-01">BUTA-06-X-STAN-01</a>.]]>')
newPart.addTag('oompClass','Surface Mount')
newPart.addTag('oompClassCode','SMDS')
newPart.addTag('oompDiag','rectangle;0;0;6.2;6.2;Main Square')
newPart.addTag('oompDiag','circle;0;0;3.5;3.5;Main Button')
newPart.addTag('oompDiag','circle;2.15;2.15;0.75;0.75;Circle Nub 1')
newPart.addTag('oompDiag','circle;-2.15;-2.15;0.75;0.75;Circle Nub 2')
newPart.addTag('oompDiag','circle;2.15;-2.15;0.75;0.75;Circle Nub 3')
newPart.addTag('oompDiag','circle;-2.15;2.15;0.75;0.75;Circle Nub 4')
newPart.addTag('oompDiag','rectangle;3.8;2.25;1.4;0.7;pad 1')
newPart.addTag('oompDiag','rectangle;-3.8;-2.25;1.4;0.7;pad 2')
newPart.addTag('oompDiag','rectangle;-3.8;2.25;1.4;0.7;pad 3')
newPart.addTag('oompDiag','rectangle;3.8;-2.25;1.4;0.7;pad 4')
newPart.addTag('oompDiag','name;0;5;20;5;##name@@')
newPart.addTag('oompDiag','oompURL;0;-5;2.835;##hexID@@')
newPart.addTag('oompSchem','template;BUTA-XXXX-X-XXXX-XX-schem')
newPart.addTag('ooDesignator','S')
newPart.addTag('oompSymbol','twoSidedPackage;##ooNumPins@@/2')
newPart.addTag('ooPin1','.')
newPart.addTag('ooPin2','.')
newPart = OOMPtags.addTags(newPart,"BUTA-06-X-SMDS-01",pins = 4)
OOMP.parts.append(newPart)
