import OOMP
newPart = OOMP.getPartByID("RESE-0603-X-O471-01")

newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-1904-STAN-01', 'ID': 'R1'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-1904-STAN-01', 'ID': 'R2'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2226-STAN-01', 'ID': 'R1'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-3201-STAN-01', 'ID': 'R13'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-3201-STAN-01', 'ID': 'R14'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-4740-STAN-01', 'ID': 'R3'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-11343-STAN-01', 'ID': 'R8'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-11520-STAN-01', 'ID': 'R9'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-12000-STAN-01', 'ID': 'R6'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-12000-STAN-01', 'ID': 'R7'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-12660-STAN-01', 'ID': 'R21'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-12660-STAN-01', 'ID': 'R22'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-13911-STAN-01', 'ID': 'R6'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-14006-STAN-01', 'ID': 'R6'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-14006-STAN-01', 'ID': 'R7'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-14030-STAN-01', 'ID': 'R1'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-14051-STAN-01', 'ID': 'R4'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-14051-STAN-01', 'ID': 'R6'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-14051-STAN-01', 'ID': 'R16'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-14380-STAN-01', 'ID': 'R9'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-14414-STAN-01', 'ID': 'R3'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-14414-STAN-01', 'ID': 'R6'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-14414-STAN-01', 'ID': 'R11'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-14430-STAN-01', 'ID': 'R1'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-14554-STAN-01', 'ID': 'R6'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-14554-STAN-01', 'ID': 'R7'})