import OOMP
newPart = OOMP.getPartByID("RESE-0603-X-O203-01")

newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-3000-STAN-01', 'ID': 'R11'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-5335-STAN-01', 'ID': 'R1'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-5335-STAN-01', 'ID': 'R2'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-5335-STAN-01', 'ID': 'R6'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-10025-STAN-01', 'ID': 'R7'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-10025-STAN-01', 'ID': 'R8'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-10101-STAN-01', 'ID': 'R6'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-12009-STAN-01', 'ID': 'R5'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-12009-STAN-01', 'ID': 'R9'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-12779-STAN-01', 'ID': 'R3'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-12779-STAN-01', 'ID': 'R4'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-12858-STAN-01', 'ID': 'R2'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-12858-STAN-01', 'ID': 'R3'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-12858-STAN-01', 'ID': 'R4'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-12858-STAN-01', 'ID': 'R8'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-12858-STAN-01', 'ID': 'R9'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-12858-STAN-01', 'ID': 'R10'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-12859-STAN-01', 'ID': 'R1'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-12859-STAN-01', 'ID': 'R2'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-12859-STAN-01', 'ID': 'R3'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-12859-STAN-01', 'ID': 'R4'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-12859-STAN-01', 'ID': 'R5'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-12859-STAN-01', 'ID': 'R10'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-12859-STAN-01', 'ID': 'R11'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-12859-STAN-01', 'ID': 'R12'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-12859-STAN-01', 'ID': 'R20'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-12938-STAN-01', 'ID': 'R4'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-12938-STAN-01', 'ID': 'R5'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-12938-STAN-01', 'ID': 'R6'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-12938-STAN-01', 'ID': 'R7'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-13230-STAN-01', 'ID': 'R1'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-13261-STAN-01', 'ID': 'R16'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-13714-STAN-01', 'ID': 'R5'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-13714-STAN-01', 'ID': 'R6'})