import OOMP 
import OOMPtags 

######  Auto translated oomp file

newPart = OOMP.oompItem()
pitch = 2.54 
pins = 10
newPart.addTag('index','9876')
newPart.addTag('oompID','HEAS-I01-X-PI10-01')
newPart.addTag('hexID','HS10')
newPart.addTag('oompSort','A010110')
newPart.addTag('oompType','HEAS')
newPart.addTag('oompSize','I01')
newPart.addTag('oompColor','X')
newPart.addTag('oompDesc','PI10')
newPart.addTag('oompIndex','01')
newPart.addTag('oompVersion','99')
newPart.addTag('oompSkip','true')
newPart.addTag('ooPitch','2.54 mm')
newPart.addTag('ooWidth','25.4 mm')
newPart.addTag('ooHeight','11.65mm')
newPart.addTag('ooLength','2.54 mm')
newPart.addTag('ooFootprint','OOMP-HEAD-I01-X-PI10-01')
newPart.addTag('ooNumPins','10')
newPart.addTag('oompAbout','A commonly used 10 pin 2.54 mm spaced female header. Nice to use for a connector to another PCB (via a header like <a href="http://learn.oomlout.co.uk/OO/Projects/oomp/part/HEAD-I01-X-PI10-01">2.54 mm 10 Pin Header</a>) or to connect jumper wires to your project.')
newPart.addTag('useID','1')
newPart.addTag('importance','1')
newPart.addTag('useTitle','Arduino Output Strip')
newPart.addTag('useDescription','Used as the input strip on the Arduino UNO board for the upper digital inputs (8-13) (and compatible)')
newPart.addTag('oompClass','Through Hole Component')
newPart.addTag('oompClassCode','THTH')
newPart.addTag('oompBbls','variable;clear')
newPart.addTag('oompBbls','variable;pins;10')
newPart.addTag('oompBbls','template;XXXX-I01-X-XX-01-bbls')
newPart.addTag('oompDiag','variable;clear')
newPart.addTag('oompDiag','variable;pins;10')
newPart.addTag('oompDiag','template;HEAS-I01-X-XX-01-diag')
newPart.addTag('drawItem','variable;clear')
newPart.addTag('drawItem','variable;pins;10')
newPart.addTag('drawItem','template;XXXX-I01-X-XX-01-iden')
newPart.addTag('oompSchem','variable;clear')
newPart.addTag('oompSchem','variable;pins;10')
newPart.addTag('oompSchem','template;XXXX-XX-X-XX-01-PINS-EVEN-schem')
newPart.addTag('oompSimp','variable;clear')
newPart.addTag('oompSimp','variable;pins;10')
newPart.addTag('oompSimp','template;XXXX-I01-X-XX-01-simp')
newPart.addTag('ooDesignator','J1')
newPart = OOMPtags.addTags(newPart,"HEAS-I01-X-PI10-01",pitch = 2.54 ,pins = 10)
OOMP.parts.append(newPart)
