import OOMP 
import OOMPtags 

######  Auto translated oomp file

newPart = OOMP.oompItem()
pins = 8
newPart.addTag('index','4290')
newPart.addTag('oompID','HEAF-I01-Y-PI08-01')
newPart.addTag('name','2.54 mm 8 Pin Yellow Female Header')
newPart.addTag('hexID','10C2')
newPart.addTag('oompSort','010803')
newPart.addTag('oompType','HEAF')
newPart.addTag('oompSize','I01')
newPart.addTag('oompColor','Y')
newPart.addTag('oompDesc','PI08')
newPart.addTag('oompIndex','01')
newPart.addTag('oompVersion','99')
newPart.addTag('ooManufacturer','C-YXCO')
newPart.addTag('ooManufacturerPartNumber','F185-1108A1BSYC1')
newPart.addTag('ooNumPins','8')
newPart.addTag('ooFootprint','OOMP-HEAD-I01-X-PI08-01')
newPart.addTag('ooSEEEDsku','3460590P1')
newPart.addTag('ooSEEEDdesc','DIP Yellow Female Header')
newPart.addTag('ooSEEED3dModel','http://www.seeedstudio.com/wiki/File:1X8P-2.54-8.5-YELLOW-FEMALE.zip')
newPart.addTag('oompBbls','variable;clear')
newPart.addTag('oompBbls','variable;pins;8')
newPart.addTag('oompBbls','template;XXXX-I01-X-XX-01-bbls')
newPart.addTag('oompDiag','variable;clear')
newPart.addTag('oompDiag','variable;pins;8')
newPart.addTag('oompDiag','template;HEAF-I01-X-XX-01-diag')
newPart.addTag('drawItem','variable;clear')
newPart.addTag('drawItem','variable;pins;8')
newPart.addTag('drawItem','template;XXXX-I01-X-XX-01-iden')
newPart.addTag('oompSchem','variable;clear')
newPart.addTag('oompSchem','variable;pins;8')
newPart.addTag('oompSchem','template;XXXX-XX-X-XX-01-PINS-EVEN-schem')
newPart.addTag('oompSimp','variable;clear')
newPart.addTag('oompSimp','variable;pins;8')
newPart.addTag('oompSimp','template;XXXX-I01-X-XX-01-simp')
newPart.addTag('ooDesignator','J1')
newPart = OOMPtags.addTags(newPart,"HEAF-I01-Y-PI08-01",pins = 8)
OOMP.parts.append(newPart)
