import OOMP
newPart = OOMP.getPartByID("RESE-0603-X-O100-01")

newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-3201-STAN-01', 'ID': 'R12'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-3321-STAN-01', 'ID': 'R1'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-3787-STAN-01', 'ID': 'R5'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-4300-STAN-01', 'ID': 'R23'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-4313-STAN-01', 'ID': 'R5'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-4393-STAN-01', 'ID': 'R5'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-4500-STAN-01', 'ID': 'R5'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-4500-STAN-01', 'ID': 'R6'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-4506-STAN-01', 'ID': 'R5'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-4740-STAN-01', 'ID': 'R4'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-5206-STAN-01', 'ID': 'R5'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-5393-STAN-01', 'ID': 'R5'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-12660-STAN-01', 'ID': 'R9'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-13810-STAN-01', 'ID': 'R37'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-13810-STAN-01', 'ID': 'R38'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-13810-STAN-01', 'ID': 'R39'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-13810-STAN-01', 'ID': 'R40'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-13810-STAN-01', 'ID': 'R41'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-13810-STAN-01', 'ID': 'R42'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-13810-STAN-01', 'ID': 'R43'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-13810-STAN-01', 'ID': 'R44'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-14006-STAN-01', 'ID': 'R27'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-14554-STAN-01', 'ID': 'R27'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-15005-STAN-01', 'ID': 'R14'})