import OOMP 
import OOMPtags 

######  Auto translated oomp file

newPart = OOMP.oompItem()
newPart.addTag('oompID','ICIC-SP20-X-KHT46-01')
newPart.addTag('name',' 20 Pin SMD (SOP) Holtek HT46R066 ')
newPart.addTag('hexID','ICSKHT46')
newPart.addTag('oompSort','ICICSP20KHT46')
newPart.addTag('oompType','ICIC')
newPart.addTag('oompSize','SP20')
newPart.addTag('oompColor','X')
newPart.addTag('oompDesc','KHT46')
newPart.addTag('oompIndex','01')
newPart.addTag('oompVersion','98')
newPart.addTag('ooPin1','PA3/INT/AN3')
newPart.addTag('ooPin2','PA2/TC0/AN2')
newPart.addTag('ooPin3','PA1/TC0/AN1')
newPart.addTag('ooPin4','PA0/AN0')
newPart.addTag('ooPin5','VSS/GND')
newPart.addTag('ooPin6','PC0/AN4')
newPart.addTag('ooPin7','PC1/AN5')
newPart.addTag('ooPin8','PB0/SCOM0')
newPart.addTag('ooPin9','PB1/SCOM1')
newPart.addTag('ooPin10','PB2/SCOM2')
newPart.addTag('ooPin11','PB3/SCOM3')
newPart.addTag('ooPin12','PB4/TC0')
newPart.addTag('ooPin13','PB5/INT')
newPart.addTag('ooPin14','PC2')
newPart.addTag('ooPin15','PC3/PWM1')
newPart.addTag('ooPin16','VDD')
newPart.addTag('ooPin17','PA7/RES')
newPart.addTag('ooPin18','PA6/OSC1')
newPart.addTag('ooPin19','PA5/OSC2')
newPart.addTag('ooPin20','PA4/PWM0/TC1')
newPart.addTag('oompBbls','template;ICIC-SP20-X-XXXX-01-bbls')
newPart.addTag('oompDiag','template;ICIC-SP20-X-XXXX-01-diag')
newPart.addTag('oompIden','template;ICIC-SP20-X-XXXX-01-iden')
newPart.addTag('oompSimp','template;ICIC-SP20-X-XXXX-01-simp')
newPart.addTag('ooPackageMarking','HT46R066B')
newPart.addTag('ooDesignator','U1')
newPart = OOMPtags.addTags(newPart,"ICIC-SP20-X-KHT46-01")
OOMP.parts.append(newPart)
