import OOMP 
import OOMPtags 

######  Auto translated oomp file

newPart = OOMP.oompItem()
newPart.addTag('oompID','ICIC-SP20-X-K1620-01')
newPart.addTag('name',' 20 Pin SMD (SOP) 7 Segment 8 Digit LED Driver (TM1620) ')
newPart.addTag('hexID','ICS1620')
newPart.addTag('oompSort','ICICSP20K1620')
newPart.addTag('oompType','ICIC')
newPart.addTag('oompSize','SP20')
newPart.addTag('oompColor','X')
newPart.addTag('oompDesc','K1620')
newPart.addTag('oompIndex','01')
newPart.addTag('oompVersion','98')
newPart.addTag('ooPin1','VDD')
newPart.addTag('ooPin2','SEG1')
newPart.addTag('ooPin3','SEG2')
newPart.addTag('ooPin4','SEG3')
newPart.addTag('ooPin5','SEG4')
newPart.addTag('ooPin6','SEG5')
newPart.addTag('ooPin7','SEG6')
newPart.addTag('ooPin8','SEG7')
newPart.addTag('ooPin9','SEG8')
newPart.addTag('ooPin10','GRID6')
newPart.addTag('ooPin11','GRID5')
newPart.addTag('ooPin12','GND')
newPart.addTag('ooPin13','GRID4')
newPart.addTag('ooPin14','GRID3')
newPart.addTag('ooPin15','GND')
newPart.addTag('ooPin16','GRID2')
newPart.addTag('ooPin17','GRID1')
newPart.addTag('ooPin18','DIN')
newPart.addTag('ooPin19','CLK')
newPart.addTag('ooPin20','STB')
newPart.addTag('oompBbls','template;ICIC-SP20-X-XXXX-01-bbls')
newPart.addTag('oompDiag','template;ICIC-SP20-X-XXXX-01-diag')
newPart.addTag('oompIden','template;ICIC-SP20-X-XXXX-01-iden')
newPart.addTag('oompSimp','template;ICIC-SP20-X-XXXX-01-simp')
newPart.addTag('ooPackageMarking','TM1620')
newPart.addTag('ooDesignator','U1')
newPart = OOMPtags.addTags(newPart,"ICIC-SP20-X-K1620-01")
OOMP.parts.append(newPart)
