import OOMP 
import OOMPtags 

######  Auto translated oomp file

newPart = OOMP.oompItem()
newPart.addTag('index','9876')
newPart.addTag('oompID','CAPE-S63D-X-UF47-V25')
newPart.addTag('name','SMD (6.3 mm) 47 uF Capacitor (Electrolytic) 25v')
newPart.addTag('hexID','CESU047')
newPart.addTag('oompSort','S63F0.00004700000000')
newPart.addTag('oompType','CAPE')
newPart.addTag('oompSize','S63D')
newPart.addTag('oompColor','X')
newPart.addTag('oompDesc','UF47')
newPart.addTag('oompIndex','V25')
newPart.addTag('oompVersion','99')
newPart.addTag('oompSkip','true')
newPart.addTag('ooWidth','6.6')
newPart.addTag('ooHeight','5.4')
newPart.addTag('ooDiameter','6.3')
newPart.addTag('ooLength','6.6')
newPart.addTag('ooMaxVoltage','25 v')
newPart.addTag('ooTolerance','20%')
newPart.addTag('oompClass','Surface Mount')
newPart.addTag('oompClassCode','SMDS')
newPart.addTag('oompSchem','template;CAPE-XXXX-X-XXXX-XX-schem')
newPart.addTag('ooDesignator','C1')
newPart = OOMPtags.addTags(newPart,"CAPE-S63D-X-UF47-V25")
OOMP.parts.append(newPart)
