import OOMP 
import OOMPtags 

######  Auto translated oomp file

newPart = OOMP.oompItem()
pins = 8
newPart.addTag('index','4115')
newPart.addTag('oompID','RESA-1268-X-O103X4-01')
newPart.addTag('name','SMD (1206-8) 10k Ohm (x4) Resistor Array')
newPart.addTag('hexID','RA1103')
newPart.addTag('oompSort','12680010000')
newPart.addTag('oompType','RESA')
newPart.addTag('oompSize','1268')
newPart.addTag('oompColor','X')
newPart.addTag('oompDesc','O103X4')
newPart.addTag('oompIndex','01')
newPart.addTag('oompVersion','99')
newPart.addTag('ooWidth','1.6 mm')
newPart.addTag('ooLength','3.2 mm')
newPart.addTag('com','SMD')
newPart.addTag('ooPackageMarking','103')
newPart.addTag('ooNumPins','8')
newPart.addTag('ooPowerRating','62.5 mW')
newPart.addTag('ooTolerance','5%')
newPart.addTag('oompAbout','This is a small (1206 size) component that houses 4 10k Ohm resistors. Great for saving space on a project.')
newPart.addTag('useID','1')
newPart.addTag('importance','1')
newPart.addTag('useTitle','Pullup Resistor')
newPart.addTag('useDescription','Used to hold a digital pin high. When you need more than one and would like to save space.')
newPart.addTag('oompClass','Surface Mount')
newPart.addTag('oompClassCode','SMDS')
newPart.addTag('oompSchem','template;RESA-XXXX-X-XXX4-XX-schem')
newPart.addTag('ooDesignator','RN1')
newPart = OOMPtags.addTags(newPart,"RESA-1268-X-O103X4-01",pins = 8)
OOMP.parts.append(newPart)
