import OOMP 
import OOMPtags 

######  Auto translated oomp file

newPart = OOMP.oompItem()
newPart.addTag('index','4161')
newPart.addTag('oompID','RESE-W04-X-O473-01')
newPart.addTag('name','1/4 Watt 47k Ohm Resistor')
newPart.addTag('hexID','R4473')
newPart.addTag('oompSort','0W040047000')
newPart.addTag('oompType','RESE')
newPart.addTag('oompSize','W04')
newPart.addTag('oompColor','X')
newPart.addTag('oompDesc','O473')
newPart.addTag('oompIndex','01')
newPart.addTag('oompVersion','99')
newPart.addTag('ooWidth','62.8 mm')
newPart.addTag('ooDiameter','2.5 mm')
newPart.addTag('ooLength','6.8 mm')
newPart.addTag('ooMaterial','Carbon')
newPart.addTag('ooPowerRating','1/4 W')
newPart.addTag('ooMaxVoltage','500 V')
newPart.addTag('ooTolerance','5%')
newPart.addTag('oompClass','Through Hole Component')
newPart.addTag('oompClassCode','THTH')
newPart.addTag('colorBand1','YELLOW')
newPart.addTag('colorBand2','PURPLE')
newPart.addTag('colorBand3','ORANGE')
newPart.addTag('oompBbls','template;RESE-W04-X-XXXX-XX-bbls')
newPart.addTag('oompDiag','template;RESE-W04-X-XXXX-XX-diag')
newPart.addTag('oompIden','template;RESE-W04-X-XXXX-XX-iden')
newPart.addTag('oompSchem','template;RESE-XXXX-X-XXXX-XX-schem')
newPart.addTag('oompSimp','template;RESE-W04-X-XXXX-XX-simp')
newPart.addTag('ooDesignator','R1')
newPart = OOMPtags.addTags(newPart,"RESE-W04-X-O473-01")
OOMP.parts.append(newPart)
