import OOMP 
import OOMPtags 

######  Auto translated oomp file

newPart = OOMP.oompItem()
pins = 10
newPart.addTag('index','4292')
newPart.addTag('oompID','HEAS-I01-Y-PI10-01')
newPart.addTag('name','2.54 mm 10 Pin Yellow Female Header')
newPart.addTag('hexID','HF10Y')
newPart.addTag('oompSort','011003')
newPart.addTag('oompType','HEAS')
newPart.addTag('oompSize','I01')
newPart.addTag('oompColor','Y')
newPart.addTag('oompDesc','PI10')
newPart.addTag('oompIndex','01')
newPart.addTag('oompVersion','99')
newPart.addTag('ooManufacturer','C-YXCO')
newPart.addTag('ooManufacturerPartNumber','F185-1110A1BSYC1')
newPart.addTag('ooNumPins','10')
newPart.addTag('ooFootprint','OOMP-HEAD-I01-X-PI10-01')
newPart.addTag('ooSEEEDsku','3460170P1')
newPart.addTag('ooSEEEDdesc','DIP Yellow Female Header')
newPart.addTag('ooSEEED3dModel','http://www.seeedstudio.com/wiki/File:1X10P-2.54-8.5-YELLOW-FEMALE.zip')
newPart.addTag('oompBbls','variable;clear')
newPart.addTag('oompBbls','variable;pins;10')
newPart.addTag('oompBbls','template;XXXX-I01-X-XX-01-bbls')
newPart.addTag('oompDiag','variable;clear')
newPart.addTag('oompDiag','variable;pins;10')
newPart.addTag('oompDiag','template;HEAS-I01-X-XX-01-diag')
newPart.addTag('drawItem','variable;clear')
newPart.addTag('drawItem','variable;pins;10')
newPart.addTag('drawItem','template;XXXX-I01-X-XX-01-iden')
newPart.addTag('oompSchem','variable;clear')
newPart.addTag('oompSchem','variable;pins;10')
newPart.addTag('oompSchem','template;XXXX-XX-X-XX-01-PINS-EVEN-schem')
newPart.addTag('oompSimp','variable;clear')
newPart.addTag('oompSimp','variable;pins;10')
newPart.addTag('oompSimp','template;XXXX-I01-X-XX-01-simp')
newPart.addTag('ooDesignator','J1')
newPart = OOMPtags.addTags(newPart,"HEAS-I01-Y-PI10-01",pins = 10)
OOMP.parts.append(newPart)
