import OOMP
newPart = OOMP.getPartByID("RESE-0805-X-O220-01")

newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-1060-STAN-01', 'ID': 'R2'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-1060-STAN-01', 'ID': 'R3'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-1601-STAN-01', 'ID': 'R10'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-1601-STAN-01', 'ID': 'R11'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-1788-STAN-01', 'ID': 'R3'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-1788-STAN-01', 'ID': 'R4'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2298-STAN-01', 'ID': 'R10'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2298-STAN-01', 'ID': 'R11'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2455-STAN-01', 'ID': 'R10'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2455-STAN-01', 'ID': 'R11'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2616-STAN-01', 'ID': 'R22'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2616-STAN-01', 'ID': 'R23'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2661-STAN-01', 'ID': 'R4'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2661-STAN-01', 'ID': 'R5'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-3538-STAN-01', 'ID': 'R2'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-376-STAN-01', 'ID': 'R1'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-376-STAN-01', 'ID': 'R2'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-376-STAN-01', 'ID': 'R3'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-376-STAN-01', 'ID': 'R4'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-659-STAN-01', 'ID': 'R1'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-659-STAN-01', 'ID': 'R2'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-782-STAN-01', 'ID': 'R1'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-782-STAN-01', 'ID': 'R2'})