import OOMP 
import OOMPtags 

######  Auto translated oomp file

newPart = OOMP.oompItem()
pins = 16
newPart.addTag('oompID','ICIC-SP16-X-KCH340-01')
newPart.addTag('name','16 Pin SMD (SOP) USB-Serial (CH340)')
newPart.addTag('hexID','IC340')
newPart.addTag('oompSort','')
newPart.addTag('oompClass','Surface Mount')
newPart.addTag('oompClassCode','SDMS')
newPart.addTag('oompType','ICIC')
newPart.addTag('oompSize','SP16')
newPart.addTag('oompColor','X')
newPart.addTag('oompDesc','KCH340')
newPart.addTag('oompIndex','01')
newPart.addTag('oompVersion','99')
newPart.addTag('ooNumPins','16')
newPart.addTag('ooPin1','GND')
newPart.addTag('ooPin2','TXD')
newPart.addTag('ooPin3','RXD')
newPart.addTag('ooPin4','V3')
newPart.addTag('ooPin5','UD+')
newPart.addTag('ooPin6','UD-')
newPart.addTag('ooPin7','X1')
newPart.addTag('ooPin8','X0')
newPart.addTag('ooPin9','CTS#')
newPart.addTag('ooPin10','DSR#')
newPart.addTag('ooPin11','RI#')
newPart.addTag('ooPin12','DCD#')
newPart.addTag('ooPin13','DTR#')
newPart.addTag('ooPin14','RTS#')
newPart.addTag('ooPin15','R232')
newPart.addTag('ooPin16','VCC')
newPart.addTag('ooDesignator','U1')
newPart = OOMPtags.addTags(newPart,"ICIC-SP16-X-KCH340-01",pins = 16)
OOMP.parts.append(newPart)
