import OOMP
newPart = OOMP.getPartByID("DCJP-21D-X-STAN-01")

newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-10914-STAN-01', 'ID': 'JP4'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-10930-STAN-01', 'ID': 'J1'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-11007-STAN-01', 'ID': 'J2'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-11043-STAN-01', 'ID': 'J1'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-11197-STAN-01', 'ID': 'J3'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-114-STAN-01', 'ID': 'J1'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-11561-STAN-01', 'ID': 'J1'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-12885-STAN-01', 'ID': 'J2'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-13124-STAN-01', 'ID': 'JP4'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-13157-STAN-01', 'ID': 'J1'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-13288-STAN-01', 'ID': 'JP2'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-13672-STAN-01', 'ID': 'JP3'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-13714-STAN-01', 'ID': 'JP18'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-13720-STAN-01', 'ID': 'J1'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-13975-STAN-01', 'ID': 'J3'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-14155-STAN-01', 'ID': 'J2'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-14669-STAN-01', 'ID': 'J3'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-14812-STAN-01', 'ID': 'JP3'})