import OOMP 
import OOMPtags 

######  Auto translated oomp file

newPart = OOMP.oompItem()
pins = 3
newPart.addTag('index','4283')
newPart.addTag('hexID','DJ21')
newPart.addTag('oompType','DCJP')
newPart.addTag('oompSize','21D')
newPart.addTag('oompColor','X')
newPart.addTag('oompDesc','STAN')
newPart.addTag('oompIndex','01')
newPart.addTag('oompVersion','99')
newPart.addTag('ooWidth','14.2 mm')
newPart.addTag('ooHeight','11 mm')
newPart.addTag('ooLength','9 mm')
newPart.addTag('ooManufacturer','C-BEST')
newPart.addTag('ooManufacturerPartNumber','DC-005')
newPart.addTag('ooNumPins','3')
newPart.addTag('ooFootprint','OOMP-DCJP-21D-X-STAN-01')
newPart.addTag('useID','1')
newPart.addTag('useID','1')
newPart.addTag('importance','1')
newPart.addTag('importance','1')
newPart.addTag('useTitle','DC Input')
newPart.addTag('useTitle','Arduino Power')
newPart.addTag('useDescription','a socket for low voltage DC power.')
newPart.addTag('useDescription','Used as the power adapter jack on the Arduino UNO')
newPart.addTag('ooSEEEDsku','3410020P1')
newPart.addTag('ooSEEEDdesc','CONN POWER JACK 2.1MM')
newPart.addTag('oompAbout','A commonly used adapter for connecting DC power to a project. Often reffered to as a barrel jack. It is common (although not always) practice to wire these up centre pin positive.')
newPart.addTag('ooSEEED3dModel','http://www.seeedstudio.com/wiki/File:PW-3P-2.1.zip')
newPart.addTag('oompClass','Through Hole Component')
newPart.addTag('oompClassCode','THTH')
newPart.addTag('ooDesignator','J1')
newPart = OOMPtags.addTags(newPart,"DCJP-21D-X-STAN-01",pins = 3)
OOMP.parts.append(newPart)
