import OOMP 
import OOMPtags 

######  Auto translated oomp file

newPart = OOMP.oompItem()
pins = 18
newPart.addTag('index','9876')
newPart.addTag('oompID','ICIC-DI18-X-K2803-01')
newPart.addTag('name','18 Pin DIP ULN2803A Octal Transistor Array')
newPart.addTag('hexID','IC2803')
newPart.addTag('oompSort','ULN2803A')
newPart.addTag('oompType','ICIC')
newPart.addTag('oompSize','DI18')
newPart.addTag('oompColor','X')
newPart.addTag('oompDesc','K2803')
newPart.addTag('oompIndex','01')
newPart.addTag('oompVersion','99')
newPart.addTag('ooNumPins','18')
newPart.addTag('ooFootprint','OOMP-ICIC-DI18-X-XXXX-01')
newPart.addTag('oompClass','Through Hole Component')
newPart.addTag('oompClassCode','THTH')
newPart.addTag('ooDesignator','U1')
newPart.addTag('ooPin1','IN1')
newPart.addTag('ooPin2','IN2')
newPart.addTag('ooPin3','IN3')
newPart.addTag('ooPin4','IN4')
newPart.addTag('ooPin5','IN5')
newPart.addTag('ooPin6','IN6')
newPart.addTag('ooPin7','IN7')
newPart.addTag('ooPin8','IN8')
newPart.addTag('ooPin9','GND')
newPart.addTag('ooPin10','COM')
newPart.addTag('ooPin11','OUT8')
newPart.addTag('ooPin12','OUT7')
newPart.addTag('ooPin13','OUT6')
newPart.addTag('ooPin14','OUT5')
newPart.addTag('ooPin15','OUT4')
newPart.addTag('ooPin16','OUT3')
newPart.addTag('ooPin17','OUT2')
newPart.addTag('ooPin18','OUT1')
newPart = OOMPtags.addTags(newPart,"ICIC-DI18-X-K2803-01",pins = 18)
OOMP.parts.append(newPart)
