import OOMP 
import OOMPtags 

######  Auto translated oomp file

newPart = OOMP.oompItem()
pitch = 2.54 
newPart.addTag('oompID','MOSN-T220-X-A23-01')
newPart.addTag('name','TO-220 23 Amp N-Ch. MOSFET')
newPart.addTag('oompSort','')
newPart.addTag('oompType','MOSN')
newPart.addTag('oompSize','T220')
newPart.addTag('oompColor','X')
newPart.addTag('oompDesc','A23')
newPart.addTag('oompIndex','01')
newPart.addTag('oompVersion','999')
newPart.addTag('hexID','MN220A23')
newPart.addTag('ooPitch','2.54 mm')
newPart.addTag('oonumPins','3')
newPart.addTag('oonumRows','1')
newPart.addTag('oopin1','G')
newPart.addTag('oopin1X','0')
newPart.addTag('ooPin1Y','0')
newPart.addTag('oopin2','D')
newPart.addTag('oopin2X','0')
newPart.addTag('ooPin2Y','0.1"')
newPart.addTag('oopin3','S')
newPart.addTag('oopin3X','0')
newPart.addTag('ooPin3Y','0.2"')
newPart.addTag('oompSymbol','oneSidedPackage;##ooNumPins@@')
newPart.addTag('oompFootprint','oneSidedPackage;##ooNumPins@@;##ooPitch@@')
newPart.addTag('oompBbls','template;XXXX-T220-X-XXXX-01-bbls')
newPart.addTag('oompDiag','template;XXXX-T220-X-XXXX-01-diag')
newPart.addTag('oompIden','template;XXXX-T220-X-XXXX-01-iden')
newPart.addTag('oompSimp','template;XXXX-T220-X-XXXX-01-simp')
newPart.addTag('ooDesignator','Q1')
newPart = OOMPtags.addTags(newPart,"MOSN-T220-X-A23-01",pitch = 2.54 )
OOMP.parts.append(newPart)
