import OOMP 
import OOMPtags 

######  Auto translated oomp file

newPart = OOMP.oompItem()
pitch = 2.54 
pins = 36
newPart.addTag('index','3969')
newPart.addTag('oompID','HEAL-I01-X-PI36-01')
newPart.addTag('name','2.54 mm 36 Pin Header (Long)')
newPart.addTag('hexID','HL36')
newPart.addTag('oompSort','010136')
newPart.addTag('oompType','HEAL')
newPart.addTag('oompSize','I01')
newPart.addTag('oompColor','X')
newPart.addTag('oompDesc','PI36')
newPart.addTag('oompIndex','01')
newPart.addTag('oompVersion','10')
newPart.addTag('ooPitch','2.54 mm')
newPart.addTag('ooWidth','91.44 mm')
newPart.addTag('ooHeight','14.54mm')
newPart.addTag('ooDepth','2.54mm')
newPart.addTag('ooNumPins','36')
newPart.addTag('ooFootprint','OOMP-HEAD-I01-X-PI36-01')
newPart.addTag('ooMaxCurrent','3A')
newPart.addTag('ooMaxVoltage','1000V')
newPart.addTag('oompAbout','These 36 pin strips are by far the most common length. They are designed to be snapped to any length (using either pliers or snips) so are the most useful to have in your toolbox.')
newPart.addTag('oompClass','Through Hole Component')
newPart.addTag('oompClassCode','THTH')
newPart.addTag('oompBbls','variable;clear')
newPart.addTag('oompBbls','variable;pins;36')
newPart.addTag('oompBbls','template;XXXX-I01-X-XX-01-bbls')
newPart.addTag('oompDiag','variable;clear')
newPart.addTag('oompDiag','variable;pins;36')
newPart.addTag('oompDiag','template;HEAL-I01-X-XX-01-diag')
newPart.addTag('drawItem','variable;clear')
newPart.addTag('drawItem','variable;pins;36')
newPart.addTag('drawItem','template;XXXX-I01-X-XX-01-iden')
newPart.addTag('oompSchem','variable;clear')
newPart.addTag('oompSchem','variable;pins;36')
newPart.addTag('oompSchem','template;XXXX-XX-X-XX-01-PINS-EVEN-schem')
newPart.addTag('oompSimp','variable;clear')
newPart.addTag('oompSimp','variable;pins;36')
newPart.addTag('oompSimp','template;XXXX-I01-X-XX-01-simp')
newPart.addTag('ooDesignator','J1')
newPart = OOMPtags.addTags(newPart,"HEAL-I01-X-PI36-01",pitch = 2.54 ,pins = 36)
OOMP.parts.append(newPart)
