import OOMP 
import OOMPtags 

######  Auto translated oomp file

newPart = OOMP.oompItem()
pins = 6
newPart.addTag('oompID','HEAF-I01-W-PI06-01')
newPart.addTag('name','2.54 mm 6 Pin White Female Header')
newPart.addTag('hexID','H6W')
newPart.addTag('oompSort','')
newPart.addTag('oompClass','Through Hole')
newPart.addTag('oompClassCode','THTH')
newPart.addTag('oompType','HEAF')
newPart.addTag('oompSize','I01')
newPart.addTag('oompColor','W')
newPart.addTag('oompDesc','PI06')
newPart.addTag('oompIndex','01')
newPart.addTag('oompVersion','40')
newPart.addTag('ooNumPins','6')
newPart.addTag('ooFootprint','OOMP-HEAD-I01-X-PI06-01')
newPart.addTag('oompBbls','variable;clear')
newPart.addTag('oompBbls','variable;pins;6')
newPart.addTag('oompBbls','template;XXXX-I01-X-XX-01-bbls')
newPart.addTag('oompDiag','variable;clear')
newPart.addTag('oompDiag','variable;pins;6')
newPart.addTag('oompDiag','template;HEAF-I01-X-XX-01-diag')
newPart.addTag('drawItem','variable;clear')
newPart.addTag('drawItem','variable;pins;6')
newPart.addTag('drawItem','template;XXXX-I01-X-XX-01-iden')
newPart.addTag('oompSchem','variable;clear')
newPart.addTag('oompSchem','variable;pins;6')
newPart.addTag('oompSchem','template;XXXX-XX-X-XX-01-PINS-EVEN-schem')
newPart.addTag('oompSimp','variable;clear')
newPart.addTag('oompSimp','variable;pins;6')
newPart.addTag('oompSimp','template;XXXX-I01-X-XX-01-simp')
newPart.addTag('ooDesignator','J1')
newPart = OOMPtags.addTags(newPart,"HEAF-I01-W-PI06-01",pins = 6)
OOMP.parts.append(newPart)
