import OOMP
newPart = OOMP.getPartByID("TERS-35D-L-PI03-01")

newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-1752-STAN-01', 'ID': 'X1'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2923-STAN-01', 'ID': 'X2'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2926-STAN-01', 'ID': 'X5'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2926-STAN-01', 'ID': 'X6'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2926-STAN-01', 'ID': 'X7'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2926-STAN-01', 'ID': 'X8'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2926-STAN-01', 'ID': 'X9'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2926-STAN-01', 'ID': 'X10'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2926-STAN-01', 'ID': 'X11'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2926-STAN-01', 'ID': 'X12'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-4409-STAN-01', 'ID': 'X3'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-4759-STAN-01', 'ID': 'X4'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-10124-STAN-01', 'ID': 'JP2'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-12959-STAN-01', 'ID': 'JP4'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-13261-STAN-01', 'ID': 'JP4'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-13815-STAN-01', 'ID': 'J2'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-14153-STAN-01', 'ID': 'J7'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-14155-STAN-01', 'ID': 'J3'})