import OOMP 
import OOMPtags 

######  Auto translated oomp file

newPart = OOMP.oompItem()
newPart.addTag('oompID','RESE-0603-X-O103-67')
newPart.addTag('name','SMD (0603) 10k Ohm Resistor 1%')
newPart.addTag('hexID','R6103A')
newPart.addTag('oompDesc','O103')
newPart.addTag('oompSort','ZZZ06030010000')
newPart.addTag('oompType','RESE')
newPart.addTag('oompSize','0603')
newPart.addTag('oompColor','X')
newPart.addTag('oompIndex','67')
newPart.addTag('oompVersion','999')
newPart.addTag('ooWidth','0.8mm')
newPart.addTag('ooHeight','0.45mm')
newPart.addTag('ooLength','1.6mm')
newPart.addTag('ooTolerance','1%')
newPart.addTag('ooMaterial','Carbon Film')
newPart.addTag('ooMaxVoltage','50 V')
newPart.addTag('oompBbls','template;XXXX-0603-X-XXXX-XX-bbls')
newPart.addTag('oompDiag','template;XXXX-0603-X-XXXX-XX-diag')
newPart.addTag('oompIden','template;XXXX-0603-X-XXXX-XX-iden')
newPart.addTag('oompSchem','template;RESE-XXXX-X-XXXX-XX-schem')
newPart.addTag('oompSimp','template;XXXX-0603-X-XXXX-XX-simp')
newPart.addTag('ooDesignator','R1')
newPart = OOMPtags.addTags(newPart,"RESE-0603-X-O103-67")
OOMP.parts.append(newPart)
