import OOMP
newPart = OOMP.getPartByID("HEAD-I01-X-PI14-01")

newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-1752-STAN-01', 'ID': 'JP2'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2133-STAN-01', 'ID': 'CONTROL'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2133-STAN-01', 'ID': 'GPIO1'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-3677-STAN-01', 'ID': 'JP2'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-3677-STAN-01', 'ID': 'JP4'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-3727-STAN-01', 'ID': 'JP2'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-3727-STAN-01', 'ID': 'JP4'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-3800-STAN-01', 'ID': 'JP2'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-3800-STAN-01', 'ID': 'JP4'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-4363-STAN-01', 'ID': 'JP2'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-4363-STAN-01', 'ID': 'JP4'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-4481-STAN-01', 'ID': 'JP2'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-4481-STAN-01', 'ID': 'JP4'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-4888-STAN-01', 'ID': 'JP2'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-4888-STAN-01', 'ID': 'JP4'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ARDU-UNO-REV3-SM', 'ID': 'J1'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-10116-STAN-01', 'ID': 'JP1'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-10116-STAN-01', 'ID': 'JP5'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-11520-STAN-01', 'ID': 'JP1'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-11520-STAN-01', 'ID': 'JP2'})