import OOMP
newPart = OOMP.getPartByID("HEAD-I01-X-PI14-01")

newPart.addTag('footprintEagle','SparkFun-Eagle-Libraries/Sparkfun-Connectors/1X14')
newPart.addTag('footprintEagle','SparkFun-Eagle-Libraries/Sparkfun-Connectors/1X14_LOCK')
newPart.addTag('footprintEagle','SparkFun-Eagle-Libraries/Sparkfun-Connectors/1X14_LOCK_LONGPADS')
newPart.addTag('footprintEagle','SparkFun-Eagle-Libraries/Sparkfun-Connectors/1X14_NO_SILK')
newPart.addTag('footprintEagle','SparkFun-Eagle-Libraries-Sparkfun-Connectors-1X14')
newPart.addTag('footprintEagle','SparkFun-Eagle-Libraries-Sparkfun-Connectors-1X14_LOCK')
newPart.addTag('footprintEagle','SparkFun-Eagle-Libraries-Sparkfun-Connectors-1X14_LOCK_LONGPADS')
newPart.addTag('footprintEagle','SparkFun-Eagle-Libraries-Sparkfun-Connectors-1X14_NO_SILK')
newPart.addTag('footprintEagle','FOOTPRINT-eagle-Adafruit-Eagle-Library-adafruit-1X14')
newPart.addTag('footprintEagle','FOOTPRINT-eagle-Adafruit-Eagle-Library-adafruit-1X14-CB')
newPart.addTag('footprintEagle','FOOTPRINT-eagle-Pimoroni-Eagle-Library-pimoroni-headers-114')
newPart.addTag('footprintKicad','kicad-footprints/Connector_PinHeader_2.54mm/PinHeader_1x14_P2.54mm_Vertical')
newPart.addTag('footprintKicad','kicad-footprints/Connector_PinHeader_2.54mm/PinHeader_1x14_P2.54mm_Vertical')