import OOMP 
import OOMPtags 

######  Auto translated oomp file

newPart = OOMP.oompItem()
pitch = 2.54 
pins = 15
newPart.addTag('oompID','HEAS-I01-X-PI15-01')
newPart.addTag('hexID','HS15')
newPart.addTag('oompSort','A010115')
newPart.addTag('oompType','HEAS')
newPart.addTag('oompSize','I01')
newPart.addTag('oompColor','X')
newPart.addTag('oompDesc','PI15')
newPart.addTag('oompIndex','01')
newPart.addTag('oompVersion','99')
newPart.addTag('oompSkip','true')
newPart.addTag('ooPitch','2.54 mm')
newPart.addTag('ooWidth','38.1 mm')
newPart.addTag('ooHeight','11.65mm')
newPart.addTag('ooLength','2.54 mm')
newPart.addTag('ooFootprint','OOMP-HEAD-I01-X-PI15-01')
newPart.addTag('ooNumPins','15')
newPart.addTag('oompAbout','A commonly used 15 pin 2.54 mm spaced female header. Nice to use for a connector to another PCB (via a header like <a href="http://learn.oomlout.co.uk/OO/Projects/oomp/part/HEAD-I01-X-PI10-01">2.54 mm 10 Pin Header</a>) or to connect jumper wires to your project.')
newPart.addTag('oompClass','Through Hole Component')
newPart.addTag('oompClassCode','THTH')
newPart.addTag('oompBbls','variable;clear')
newPart.addTag('oompBbls','variable;pins;15')
newPart.addTag('oompBbls','template;XXXX-I01-X-XX-01-bbls')
newPart.addTag('oompDiag','variable;clear')
newPart.addTag('oompDiag','variable;pins;15')
newPart.addTag('oompDiag','template;HEAS-I01-X-XX-01-diag')
newPart.addTag('drawItem','variable;clear')
newPart.addTag('drawItem','variable;pins;15')
newPart.addTag('drawItem','template;XXXX-I01-X-XX-01-iden')
newPart.addTag('oompSchem','variable;clear')
newPart.addTag('oompSchem','variable;pins;15')
newPart.addTag('oompSchem','template;XXXX-XX-X-XX-01-PINS-ODD-schem')
newPart.addTag('oompSimp','variable;clear')
newPart.addTag('oompSimp','variable;pins;15')
newPart.addTag('oompSimp','template;XXXX-I01-X-XX-01-simp')
newPart.addTag('ooDesignator','J1')
newPart = OOMPtags.addTags(newPart,"HEAS-I01-X-PI15-01",pitch = 2.54 ,pins = 15)
OOMP.parts.append(newPart)
