import OOMP 
import OOMPtags 

######  Auto translated oomp file

newPart = OOMP.oompItem()
pins = 28
newPart.addTag('oompID','ICIC-QFN28-X-K4988-01')
newPart.addTag('name','28 Pin SMD (QFN) Stepper Motor Driver (A4988)')
newPart.addTag('hexID','IC4988')
newPart.addTag('oompSort','')
newPart.addTag('oompType','ICIC')
newPart.addTag('oompSize','QFN28')
newPart.addTag('oompColor','X')
newPart.addTag('oompDesc','K4988')
newPart.addTag('oompIndex','01')
newPart.addTag('oompVersion','98')
newPart.addTag('ooNumPins','28')
newPart.addTag('ooPin1','OUT2B')
newPart.addTag('ooPin2','ENABLE')
newPart.addTag('ooPin3','GND')
newPart.addTag('ooPin4','CP1')
newPart.addTag('ooPin5','CP2')
newPart.addTag('ooPin6','VCP')
newPart.addTag('ooPin7','NC')
newPart.addTag('ooPin8','VREG')
newPart.addTag('ooPin9','MS1')
newPart.addTag('ooPin10','MS2')
newPart.addTag('ooPin11','MS3')
newPart.addTag('ooPin12','RESET')
newPart.addTag('ooPin13','ROSC')
newPart.addTag('ooPin14','SLEEP')
newPart.addTag('ooPin15','VDD')
newPart.addTag('ooPin16','STEP')
newPart.addTag('ooPin17','REF')
newPart.addTag('ooPin18','GND')
newPart.addTag('ooPin19','DIR')
newPart.addTag('ooPin20','NC')
newPart.addTag('ooPin21','OUT1B')
newPart.addTag('ooPin22','VBB1')
newPart.addTag('ooPin23','SENSE1')
newPart.addTag('ooPin24','OUT1A')
newPart.addTag('ooPin25','NC')
newPart.addTag('ooPin26','OUT2A')
newPart.addTag('ooPin27','SENSE2')
newPart.addTag('ooPin28','VBB2')
newPart.addTag('ooPackageMarking','A4988')
newPart.addTag('oompBbls','template;ICIC-QFN28-X-XXXX-01-bbls')
newPart.addTag('oompDiag','template;ICIC-QFN28-X-XXXX-01-diag')
newPart.addTag('oompIden','template;ICIC-QFN28-X-XXXX-01-iden')
newPart.addTag('oompSimp','template;ICIC-QFN28-X-XXXX-01-simp')
newPart.addTag('ooDesignator','U1')
newPart = OOMPtags.addTags(newPart,"ICIC-QFN28-X-K4988-01",pins = 28)
OOMP.parts.append(newPart)
