import OOMP 
import OOMPtags 

######  Auto translated oomp file

newPart = OOMP.oompItem()
newPart.addTag('index','4085')
newPart.addTag('oompID','CAPT-1206-X-UF10-V10')
newPart.addTag('name','SMD (1206) 10 uF Capacitor (Tantalum) 10v')
newPart.addTag('hexID','CTS1U010B')
newPart.addTag('oompSort','12060.00000100000000')
newPart.addTag('oompType','CAPT')
newPart.addTag('oompSize','1206')
newPart.addTag('oompColor','X')
newPart.addTag('oompDesc','UF10')
newPart.addTag('oompIndex','V10')
newPart.addTag('oompVersion','99')
newPart.addTag('ooWidth','1.6 mm')
newPart.addTag('ooLength','3.2 mm')
newPart.addTag('ooManufacturer','AVX')
newPart.addTag('ooManufacturerPartNumber','TAJA106K010RNJ')
newPart.addTag('ooMaxVoltage','10 V')
newPart.addTag('ooTolerance','10%')
newPart.addTag('ooSEEEDsku','0130040P1')
newPart.addTag('ooSEEEDdesc','SMD CAP Tantalum 10uF-10V 10%')
newPart.addTag('oompClass','Surface Mount')
newPart.addTag('oompClassCode','SMDS')
newPart.addTag('oompBbls','template;XXXX-1206-X-XXXX-XX-bbls')
newPart.addTag('oompDiag','template;XXXX-1206-X-XXXX-XX-diag')
newPart.addTag('oompIden','template;XXXX-1206-X-XXXX-XX-iden')
newPart.addTag('oompSchem','template;CAPT-XXXX-X-XXXX-XX-schem')
newPart.addTag('oompSimp','template;XXXX-1206-X-XXXX-XX-simp')
newPart.addTag('ooDesignator','C1')
newPart = OOMPtags.addTags(newPart,"CAPT-1206-X-UF10-V10")
OOMP.parts.append(newPart)
