import OOMP 
import OOMPtags 

######  Auto translated oomp file

newPart = OOMP.oompItem()
pitch = 2.54 
newPart.addTag('index','3948')
newPart.addTag('oompID','CRHO-I01-B-PI04-01')
newPart.addTag('name','2.54 mm 4 Pin Black Crimp Housing')
newPart.addTag('hexID','CH04')
newPart.addTag('oompSort','010104')
newPart.addTag('oompType','CRHO')
newPart.addTag('oompSize','I01')
newPart.addTag('oompColor','B')
newPart.addTag('oompDesc','PI04')
newPart.addTag('oompIndex','01')
newPart.addTag('oompVersion','10')
newPart.addTag('ooPitch','2.54 mm')
newPart.addTag('ooWidth','10.36 mm')
newPart.addTag('ooHeight','14 mm')
newPart.addTag('ooDepth','2.5 mm')
newPart.addTag('ooMaterial','Plastic')
newPart.addTag('ooTerminalStyle','DuPont')
newPart.addTag('ooMaxCurrent','3 A')
newPart.addTag('ooMaxVoltage','250 V')
newPart.addTag('oompAbout','These four pin connectors are often used simply when you find you have four wires that need connecting. That said a common usage is with data buses, most notably I2C (power (+/gnd) SDA, SCL), or they can also be found on stepper motors when they are being driven in bipolar mode (A+, A-, B+, B-).')
newPart.addTag('oompClass','Through Hole Component')
newPart.addTag('oompClassCode','THTH')
newPart.addTag('oompBbls','variable;clear')
newPart.addTag('oompBbls','variable;pins;4')
newPart.addTag('oompBbls','template;XXXX-I01-X-XX-01-bbls')
newPart.addTag('oompDiag','variable;clear')
newPart.addTag('oompDiag','variable;pins;4')
newPart.addTag('oompDiag','template;CRHO-I01-X-XX-01-diag')
newPart.addTag('drawItem','variable;clear')
newPart.addTag('drawItem','variable;pins;4')
newPart.addTag('drawItem','template;XXXX-I01-X-XX-01-iden')
newPart.addTag('oompSchem','variable;clear')
newPart.addTag('oompSchem','variable;pins;4')
newPart.addTag('oompSchem','template;XXXX-XX-X-XX-01-PINS-EVEN-schem')
newPart.addTag('oompSimp','variable;clear')
newPart.addTag('oompSimp','variable;pins;4')
newPart.addTag('oompSimp','template;XXXX-I01-X-XX-01-simp')
newPart.addTag('ooDesignator','J1')
newPart = OOMPtags.addTags(newPart,"CRHO-I01-B-PI04-01",pitch = 2.54 )
OOMP.parts.append(newPart)
