import OOMP
newPart = OOMP.getPartByID("CAPC-0402-X-PF22-V50")

newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-4888-STAN-01', 'ID': 'C19'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-4888-STAN-01', 'ID': 'C20'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-4900-STAN-01', 'ID': 'C19'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-4900-STAN-01', 'ID': 'C20'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-5302-STAN-01', 'ID': 'C19'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-5302-STAN-01', 'ID': 'C20'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ARDU-DUE-STAN-01', 'ID': 'C21'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ARDU-DUE-STAN-01', 'ID': 'C22'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ARDU-DUE-STAN-01', 'ID': 'C23'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ARDU-DUE-STAN-01', 'ID': 'C24'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ARDU-DUE-STAN-01', 'ID': 'C25'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ARDU-DUE-STAN-01', 'ID': 'C39'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ARDU-DUE-STAN-01', 'ID': 'C40'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ARDU-MICRO-STAN-01', 'ID': 'C12'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ARDU-MICRO-STAN-01', 'ID': 'C13'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-10160-STAN-01', 'ID': 'C1'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-10406-STAN-01', 'ID': 'C2'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-10406-STAN-01', 'ID': 'C7'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-10587-STAN-01', 'ID': 'C3'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-10587-STAN-01', 'ID': 'C8'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-11013-STAN-01', 'ID': 'C11'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-11013-STAN-01', 'ID': 'C12'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-11058-STAN-01', 'ID': 'C4'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-11083-STAN-01', 'ID': 'C3'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-11083-STAN-01', 'ID': 'C4'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-11129-STAN-01', 'ID': 'C5'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-11129-STAN-01', 'ID': 'C6'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-11197-STAN-01', 'ID': 'C11'})