import OOMP
newPart = OOMP.getPartByID("CAPC-0805-X-UF22D-V25")

newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-1628-STAN-01', 'ID': 'C2'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-1713-STAN-01', 'ID': 'C1'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-1713-STAN-01', 'ID': 'C5'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-1752-STAN-01', 'ID': 'C5'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-1903-STAN-01', 'ID': 'C2'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-1944-STAN-01', 'ID': 'C2'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2030-STAN-01', 'ID': 'C2'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2078-STAN-01', 'ID': 'C7'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-2465-STAN-01', 'ID': 'C2'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-326-STAN-01', 'ID': 'C3'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-326-STAN-01', 'ID': 'C6'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-3531-STAN-01', 'ID': 'C3'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-3531-STAN-01', 'ID': 'C4'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-3531-STAN-01', 'ID': 'C6'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-3531-STAN-01', 'ID': 'C7'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-3531-STAN-01', 'ID': 'C8'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-3538-STAN-01', 'ID': 'C3'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-661-STAN-01', 'ID': 'C5'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-661-STAN-01', 'ID': 'C6'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-661-STAN-01', 'ID': 'C7'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-938-STAN-01', 'ID': 'C3'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-938-STAN-01', 'ID': 'C4'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-938-STAN-01', 'ID': 'C6'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-938-STAN-01', 'ID': 'C7'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-ADAF-938-STAN-01', 'ID': 'C8'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-11850-STAN-01', 'ID': 'C2'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-11850-STAN-01', 'ID': 'C4'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-11850-STAN-01', 'ID': 'C6'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-12000-STAN-01', 'ID': 'C3'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-12000-STAN-01', 'ID': 'C5'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-13035-STAN-01', 'ID': 'C1'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-13628-STAN-01', 'ID': 'C1'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-14048-STAN-01', 'ID': 'C5'})
newPart.addTag('oompInstances',{'PROJECT': 'PROJ-SPAR-14532-STAN-01', 'ID': 'C1'})