import OOMP 
import OOMPtags 

######  Auto translated oomp file

newPart = OOMP.oompItem()
newPart.addTag('oompID','DISP-16X2-G-LCD-01')
newPart.addTag('name',' 16 x 2 Character LCD Green Display ')
newPart.addTag('hexID','DS16')
newPart.addTag('oompSort','DISP16X2LCD')
newPart.addTag('oompType','DISP')
newPart.addTag('oompSize','16X2')
newPart.addTag('oompColor','G')
newPart.addTag('oompDesc','LCD')
newPart.addTag('oompIndex','01')
newPart.addTag('oompVersion','98')
newPart.addTag('ooPin1','GND')
newPart.addTag('ooPin2','5V')
newPart.addTag('ooPin3','CON')
newPart.addTag('ooPin4','RS')
newPart.addTag('ooPin5','R/W')
newPart.addTag('ooPin6','EN')
newPart.addTag('ooPin7','D1')
newPart.addTag('ooPin8','D2')
newPart.addTag('ooPin9','D3')
newPart.addTag('ooPin10','D4')
newPart.addTag('ooPin11','D5')
newPart.addTag('ooPin12','D6')
newPart.addTag('ooPin13','D7')
newPart.addTag('ooPin14','D8')
newPart.addTag('ooPin15','BL+')
newPart.addTag('ooPin16','BL-')
newPart.addTag('oompBbls','template;DISP-16X2-X-LCD-01-bbls')
newPart.addTag('ooDesignator','D1')
newPart = OOMPtags.addTags(newPart,"DISP-16X2-G-LCD-01")
OOMP.parts.append(newPart)
