import OOMP 
import OOMPtags 

######  Auto translated oomp file

newPart = OOMP.oompItem()
newPart.addTag('index','4096')
newPart.addTag('oompID','CAPT-2312-X-UF22-V25')
newPart.addTag('name','SMD (2312) 22 uF Capacitor (Tantalum) 25v')
newPart.addTag('hexID','CTS3U022')
newPart.addTag('oompSort','23120.00002200000000')
newPart.addTag('oompType','CAPT')
newPart.addTag('oompSize','2312')
newPart.addTag('oompColor','X')
newPart.addTag('oompDesc','UF22')
newPart.addTag('oompIndex','V25')
newPart.addTag('oompVersion','99')
newPart.addTag('ooWidth','3.20 mm')
newPart.addTag('ooLength','6.00 mm')
newPart.addTag('ooManufacturer','AVX')
newPart.addTag('ooManufacturerPartNumber','TAJC226K025RNJ')
newPart.addTag('ooMaxVoltage','25V')
newPart.addTag('ooTolerance','10%')
newPart.addTag('ooSEEEDsku','0130360P1')
newPart.addTag('ooSEEEDdesc','SMD CAP Tantalum 22uF-25V 10% 2312')
newPart.addTag('oompClass','Surface Mount')
newPart.addTag('oompClassCode','SMDS')
newPart.addTag('oompSchem','template;CAPT-XXXX-X-XXXX-XX-schem')
newPart.addTag('ooDesignator','C1')
newPart = OOMPtags.addTags(newPart,"CAPT-2312-X-UF22-V25")
OOMP.parts.append(newPart)
