import OOMP 
import OOMPtags 

######  Auto translated oomp file

newPart = OOMP.oompItem()
pitch = 2.54
pins = 2
newPart.addTag('oompID','HEAD-I01-W-PI02-01')
newPart.addTag('name','2.54 mm 2 Pin White Header')
newPart.addTag('hexID','H02W')
newPart.addTag('oompSort','HEADI0102PI')
newPart.addTag('oompType','HEAD')
newPart.addTag('oompSize','I01')
newPart.addTag('oompColor','W')
newPart.addTag('oompDesc','PI02')
newPart.addTag('oompIndex','01')
newPart.addTag('oompVersion','98')
newPart.addTag('ooPitch','2.54')
newPart.addTag('ooPinHeight','11.60')
newPart.addTag('ooPinWidth','0.64')
newPart.addTag('ooPinOffset','1.53')
newPart.addTag('ooNumPins','2')
newPart.addTag('ooFootprint','OOMP-HEAD-I01-X-PI02-01')
newPart.addTag('oompBbls','variable;clear')
newPart.addTag('oompBbls','variable;pins;2')
newPart.addTag('oompBbls','template;XXXX-I01-X-XX-01-bbls')
newPart.addTag('oompDiag','variable;clear')
newPart.addTag('oompDiag','variable;pins;2')
newPart.addTag('oompDiag','template;HEAD-I01-X-XX-01-diag')
newPart.addTag('drawItem','variable;clear')
newPart.addTag('drawItem','variable;pins;2')
newPart.addTag('drawItem','template;XXXX-I01-X-XX-01-iden')
newPart.addTag('oompSchem','variable;clear')
newPart.addTag('oompSchem','variable;pins;2')
newPart.addTag('oompSchem','template;XXXX-XX-X-XX-01-PINS-EVEN-schem')
newPart.addTag('oompSimp','variable;clear')
newPart.addTag('oompSimp','variable;pins;2')
newPart.addTag('oompSimp','template;XXXX-I01-X-XX-01-simp')
newPart.addTag('ooDesignator','J1')
newPart = OOMPtags.addTags(newPart,"HEAD-I01-W-PI02-01",pitch = 2.54,pins = 2)
OOMP.parts.append(newPart)
