import OOMP 
import OOMPtags 

######  Auto translated oomp file

newPart = OOMP.oompItem()
pitch = 2.54 
pins = 16
newPart.addTag('oompID','ICIC-DI16-X-KL293D-01')
newPart.addTag('name','16 Pin DIP Dual H-Bridge (L293D)')
newPart.addTag('oompSort','')
newPart.addTag('oompType','ICIC')
newPart.addTag('oompSize','DI16')
newPart.addTag('oompColor','X')
newPart.addTag('oompDesc','KL293D')
newPart.addTag('oompIndex','01')
newPart.addTag('oompVersion','999')
newPart.addTag('hexID','ICL293D')
newPart.addTag('ooPitch','2.54 mm')
newPart.addTag('ooPitchWidth','0.3"')
newPart.addTag('numRows','2')
newPart.addTag('ooNumPins','16')
newPart.addTag('ooPin1','EN1,2')
newPart.addTag('ooPin1x','0')
newPart.addTag('ooPin1y','0')
newPart.addTag('ooPin2','1IN')
newPart.addTag('ooPin2x','0')
newPart.addTag('ooPin2y','0.1')
newPart.addTag('ooPin3','1OUT')
newPart.addTag('ooPin3x','0')
newPart.addTag('ooPin3y','0.2')
newPart.addTag('ooPin4','GND')
newPart.addTag('ooPin4x','0')
newPart.addTag('ooPin4y','0.3')
newPart.addTag('ooPin5','GND')
newPart.addTag('ooPin5x','0')
newPart.addTag('ooPin5y','0.4')
newPart.addTag('ooPin6','2OUT')
newPart.addTag('ooPin6x','0')
newPart.addTag('ooPin6y','0.5')
newPart.addTag('ooPin7','2IN')
newPart.addTag('ooPin7x','0')
newPart.addTag('ooPin7y','0.6')
newPart.addTag('ooPin8','VCC')
newPart.addTag('ooPin8x','0')
newPart.addTag('ooPin8y','0.7')
newPart.addTag('ooPin9','EN3,4')
newPart.addTag('ooPin9x','0.3"')
newPart.addTag('ooPin9y','0.7"')
newPart.addTag('ooPin10','3IN')
newPart.addTag('ooPin10x','0.3"')
newPart.addTag('ooPin10y','0.6"')
newPart.addTag('ooPin11','3OUT')
newPart.addTag('ooPin11x','0.3"')
newPart.addTag('ooPin11y','0.5"')
newPart.addTag('ooPin12','GND')
newPart.addTag('ooPin12x','0.3"')
newPart.addTag('ooPin12y','0.4"')
newPart.addTag('ooPin13','GND')
newPart.addTag('ooPin13x','0.3"')
newPart.addTag('ooPin13y','0.3"')
newPart.addTag('ooPin14','4OUT')
newPart.addTag('ooPin14x','0.3"')
newPart.addTag('ooPin14y','0.2"')
newPart.addTag('ooPin15','4IN')
newPart.addTag('ooPin15x','0.3"')
newPart.addTag('ooPin15y','0.1"')
newPart.addTag('ooPin16','VMOT')
newPart.addTag('ooPin16x','0.3"')
newPart.addTag('ooPin16y','0')
newPart.addTag('oompDiag','template;ICIC-DI16-X-XXXX-01')
newPart.addTag('oompSymbol','twoSidedPackage;##ooNumPins@@')
newPart.addTag('oompFootprint','twoSidedPackage;##ooNumPins@@;##ooPitchWidth@@;##ooPitch@@')
newPart = OOMPtags.addTags(newPart,"ICIC-DI16-X-KL293D-01",pitch = 2.54 ,pins = 16)
OOMP.parts.append(newPart)
