import OOMP 
import OOMPtags 

######  Auto translated oomp file

newPart = OOMP.oompItem()
pitch = 2.54 
newPart.addTag('index','3973')
newPart.addTag('oompID','LEDS-10-W-FROS-01')
newPart.addTag('name','10 mm Frosted White LED')
newPart.addTag('hexID','L10W')
newPart.addTag('oompSort','1010W')
newPart.addTag('oompType','LEDS')
newPart.addTag('oompSize','10')
newPart.addTag('oompColor','W')
newPart.addTag('oompDesc','FROS')
newPart.addTag('oompIndex','01')
newPart.addTag('oompVersion','20')
newPart.addTag('ooPitch','2.54 mm')
newPart.addTag('ooLensColor','Frosted')
newPart.addTag('ooForwardVoltage','3.0 V')
newPart.addTag('ooForwardCurrent','15 mA')
newPart.addTag('ooIntensity','1,000 mcd')
newPart.addTag('ooPowerAngle','57 deg')
newPart.addTag('ooWavelength','')
newPart.addTag('ooChromaticityX','0.32')
newPart.addTag('ooChromaticityY','0.34')
newPart.addTag('ooFrontDiagram','OOMP-LEDS-10.png')
newPart.addTag('oompClass','Through Hole Component')
newPart.addTag('oompClassCode','THTH')
newPart.addTag('oompBbls','template;LEDS-10-X-XXXX-01-bbls')
newPart.addTag('oompDiag','template;LEDS-10-X-XXXX-01-diag')
newPart.addTag('oompIden','template;LEDS-10-X-XXXX-01-iden')
newPart.addTag('oompSchem','template;LEDS-XXXX-X-XXXX-XX-schem')
newPart.addTag('oompSimp','template;LEDS-10-X-XXXX-01-simp')
newPart.addTag('ooDesignator','D1')
newPart = OOMPtags.addTags(newPart,"LEDS-10-W-FROS-01",pitch = 2.54 )
OOMP.parts.append(newPart)
