import OOMP 
import OOMPtags 

######  Auto translated oomp file

newPart = OOMP.oompItem()
pitch = 2.54 
newPart.addTag('index','3946')
newPart.addTag('oompID','CRHO-I01-B-PI02-01')
newPart.addTag('name','2.54 mm 2 Pin Black Crimp Housing')
newPart.addTag('hexID','CH02')
newPart.addTag('oompSort','010102')
newPart.addTag('oompType','CRHO')
newPart.addTag('oompSize','I01')
newPart.addTag('oompColor','B')
newPart.addTag('oompDesc','PI02')
newPart.addTag('oompIndex','01')
newPart.addTag('oompVersion','10')
newPart.addTag('ooPitch','2.54 mm')
newPart.addTag('ooWidth','5.28 mm')
newPart.addTag('ooHeight','14 mm')
newPart.addTag('ooDepth','2.5 mm')
newPart.addTag('ooMaterial','Plastic')
newPart.addTag('ooTerminalStyle','DuPont')
newPart.addTag('ooMaxCurrent','3 A')
newPart.addTag('ooMaxVoltage','250 V')
newPart.addTag('oompAbout','This two pin housing is most often used for connecting power to a project. When doing this it&#39s best to use the convention of red for positive, and black for ground. Another common usage is when connecting an externally mounted button.')
newPart.addTag('oompClass','Through Hole Component')
newPart.addTag('oompClassCode','THTH')
newPart.addTag('oompBbls','variable;clear')
newPart.addTag('oompBbls','variable;pins;2')
newPart.addTag('oompBbls','template;XXXX-I01-X-XX-01-bbls')
newPart.addTag('oompDiag','variable;clear')
newPart.addTag('oompDiag','variable;pins;2')
newPart.addTag('oompDiag','template;CRHO-I01-X-XX-01-diag')
newPart.addTag('drawItem','variable;clear')
newPart.addTag('drawItem','variable;pins;2')
newPart.addTag('drawItem','template;XXXX-I01-X-XX-01-iden')
newPart.addTag('oompSchem','variable;clear')
newPart.addTag('oompSchem','variable;pins;2')
newPart.addTag('oompSchem','template;XXXX-XX-X-XX-01-PINS-EVEN-schem')
newPart.addTag('oompSimp','variable;clear')
newPart.addTag('oompSimp','variable;pins;2')
newPart.addTag('oompSimp','template;XXXX-I01-X-XX-01-simp')
newPart.addTag('ooDesignator','J1')
newPart = OOMPtags.addTags(newPart,"CRHO-I01-B-PI02-01",pitch = 2.54 )
OOMP.parts.append(newPart)
